# This kustomization program is used to create all of the Milo feature flag
# resources for the billing service.
#
# This is created as a component so it can be included with other
# kustomizations.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - registrations/
