// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	apiv1alpha1 "go.miloapis.com/billing/applyconfiguration/api/v1alpha1"
	internal "go.miloapis.com/billing/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=billing.miloapis.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccount"):
		return &apiv1alpha1.BillingAccountApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountBinding"):
		return &apiv1alpha1.BillingAccountBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountBindingSpec"):
		return &apiv1alpha1.BillingAccountBindingSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountBindingStatus"):
		return &apiv1alpha1.BillingAccountBindingStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountRef"):
		return &apiv1alpha1.BillingAccountRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountSpec"):
		return &apiv1alpha1.BillingAccountSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAccountStatus"):
		return &apiv1alpha1.BillingAccountStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingAddress"):
		return &apiv1alpha1.BillingAddressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingContactInfo"):
		return &apiv1alpha1.BillingContactInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BillingResponsibility"):
		return &apiv1alpha1.BillingResponsibilityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CardBillingAddress"):
		return &apiv1alpha1.CardBillingAddressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CatalogStatus"):
		return &apiv1alpha1.CatalogStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DefaultPaymentMethodRef"):
		return &apiv1alpha1.DefaultPaymentMethodRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeterBilling"):
		return &apiv1alpha1.MeterBillingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeterDefinition"):
		return &apiv1alpha1.MeterDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeterDefinitionSpec"):
		return &apiv1alpha1.MeterDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeterDefinitionStatus"):
		return &apiv1alpha1.MeterDefinitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeterMeasurement"):
		return &apiv1alpha1.MeterMeasurementApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MonitoredResourceLabel"):
		return &apiv1alpha1.MonitoredResourceLabelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MonitoredResourceType"):
		return &apiv1alpha1.MonitoredResourceTypeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MonitoredResourceTypeGVK"):
		return &apiv1alpha1.MonitoredResourceTypeGVKApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MonitoredResourceTypeSpec"):
		return &apiv1alpha1.MonitoredResourceTypeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MonitoredResourceTypeStatus"):
		return &apiv1alpha1.MonitoredResourceTypeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethod"):
		return &apiv1alpha1.PaymentMethodApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodCardDetails"):
		return &apiv1alpha1.PaymentMethodCardDetailsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodClass"):
		return &apiv1alpha1.PaymentMethodClassApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodClassParametersRef"):
		return &apiv1alpha1.PaymentMethodClassParametersRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodClassRef"):
		return &apiv1alpha1.PaymentMethodClassRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodClassSpec"):
		return &apiv1alpha1.PaymentMethodClassSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodClassStatus"):
		return &apiv1alpha1.PaymentMethodClassStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodDetails"):
		return &apiv1alpha1.PaymentMethodDetailsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodSpec"):
		return &apiv1alpha1.PaymentMethodSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodStatus"):
		return &apiv1alpha1.PaymentMethodStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentMethodUSBankAccountDetails"):
		return &apiv1alpha1.PaymentMethodUSBankAccountDetailsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PaymentTerms"):
		return &apiv1alpha1.PaymentTermsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectRef"):
		return &apiv1alpha1.ProjectRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TaxID"):
		return &apiv1alpha1.TaxIDApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
