apiVersion: apiserver.config.miloapis.com/v1alpha1
kind: BillingOperator
metricsServer:
  bindAddress: ":8443"
webhookServer: {}
nats:
  url: "tls://nats.nats-system.svc.cluster.local:4222"
  caFile: "/etc/nats-certs/ca.crt"
  certFile: "/etc/nats-certs/tls.crt"
  keyFile: "/etc/nats-certs/tls.key"
