apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- service.yaml
- service_account.yaml

images:
- name: ghcr.io/datum-cloud/billing
  newTag: latest

configMapGenerator:
- files:
  - config.yaml
  name: billing-config
  options:
    disableNameSuffixHash: true
