apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: billing.miloapis.com-billingentitlement
spec:
  serviceRef:
    name: "billing.miloapis.com"
  kind: BillingEntitlement
  plural: billingentitlements
  singular: billingentitlement
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
