apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: billing.miloapis.com-billingaccountbinding
spec:
  serviceRef:
    name: "billing.miloapis.com"
  kind: BillingAccountBinding
  plural: billingaccountbindings
  singular: billingaccountbinding
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
    - updateStatus
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
