apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: billing.miloapis.com-meterdefinition
spec:
  serviceRef:
    name: "billing.miloapis.com"
  kind: MeterDefinition
  plural: meterdefinitions
  singular: meterdefinition
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Platform
