apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: billing.miloapis.com-offer
spec:
  serviceRef:
    name: "billing.miloapis.com"
  kind: Offer
  plural: offers
  singular: offer
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
