apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: billing-operator-meterdefinitions
rules:
- apiGroups: ["billing.miloapis.com"]
  resources: ["meterdefinitions", "monitoredresourcetypes"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
