// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingAddressApplyConfiguration represents a declarative configuration of the BillingAddress type for use
// with apply.
//
// BillingAddress is a postal billing address. Country is required;
// other fields are recommended but optional because postal-address
// conventions differ widely by region.
//
// Name fields are intentionally absent: the recipient name (and
// optional business name) live on BillingContactInfo so we have a
// single source of truth for "who is being billed" and a clean 1:1
// mapping onto provider Customer records (Stripe, Adyen, etc. all
// use a single name field on the customer, not on the address).
type BillingAddressApplyConfiguration struct {
	// Country is the ISO 3166-1 alpha-2 country code (e.g. "GB",
	// "US"). Required because tax determination and currency
	// restrictions depend on it.
	Country *string `json:"country,omitempty"`
	// Line1 is the first line of the street address (typically
	// "number + street").
	Line1 *string `json:"line1,omitempty"`
	// Line2 is the second line of the street address (typically
	// apartment / suite / building).
	Line2 *string `json:"line2,omitempty"`
	// City is the locality.
	City *string `json:"city,omitempty"`
	// Region is the state, province, or county (free-form).
	Region *string `json:"region,omitempty"`
	// PostalCode is the post / zip code.
	PostalCode *string `json:"postalCode,omitempty"`
}

// BillingAddressApplyConfiguration constructs a declarative configuration of the BillingAddress type for use with
// apply.
func BillingAddress() *BillingAddressApplyConfiguration {
	return &BillingAddressApplyConfiguration{}
}

// WithCountry sets the Country field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Country field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithCountry(value string) *BillingAddressApplyConfiguration {
	b.Country = &value
	return b
}

// WithLine1 sets the Line1 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Line1 field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithLine1(value string) *BillingAddressApplyConfiguration {
	b.Line1 = &value
	return b
}

// WithLine2 sets the Line2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Line2 field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithLine2(value string) *BillingAddressApplyConfiguration {
	b.Line2 = &value
	return b
}

// WithCity sets the City field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the City field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithCity(value string) *BillingAddressApplyConfiguration {
	b.City = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithRegion(value string) *BillingAddressApplyConfiguration {
	b.Region = &value
	return b
}

// WithPostalCode sets the PostalCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostalCode field is set to the value of the last call.
func (b *BillingAddressApplyConfiguration) WithPostalCode(value string) *BillingAddressApplyConfiguration {
	b.PostalCode = &value
	return b
}
