// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BillingAccountPaymentArrangementApplyConfiguration represents a declarative configuration of the BillingAccountPaymentArrangement type for use
// with apply.
//
// BillingAccountPaymentArrangement is the active BillingArrangement's
// terms, published on the account so the portal, milo and finance read
// them from one place. Internal fields (such as the reason terms were
// granted) are deliberately not copied.
type BillingAccountPaymentArrangementApplyConfiguration struct {
	// Name is the name of the active BillingArrangement.
	Name *string `json:"name,omitempty"`
	// Type is how the account is billed.
	Type *apiv1alpha1.BillingArrangementType `json:"type,omitempty"`
	// StartsAt is when the arrangement took effect.
	StartsAt *v1.Time `json:"startsAt,omitempty"`
	// EndsAt is when the arrangement ends, if it has a fixed end.
	EndsAt *v1.Time `json:"endsAt,omitempty"`
	// Invoice carries the invoice terms when type is Invoice.
	Invoice *InvoiceArrangementTermsApplyConfiguration `json:"invoice,omitempty"`
}

// BillingAccountPaymentArrangementApplyConfiguration constructs a declarative configuration of the BillingAccountPaymentArrangement type for use with
// apply.
func BillingAccountPaymentArrangement() *BillingAccountPaymentArrangementApplyConfiguration {
	return &BillingAccountPaymentArrangementApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BillingAccountPaymentArrangementApplyConfiguration) WithName(value string) *BillingAccountPaymentArrangementApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BillingAccountPaymentArrangementApplyConfiguration) WithType(value apiv1alpha1.BillingArrangementType) *BillingAccountPaymentArrangementApplyConfiguration {
	b.Type = &value
	return b
}

// WithStartsAt sets the StartsAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartsAt field is set to the value of the last call.
func (b *BillingAccountPaymentArrangementApplyConfiguration) WithStartsAt(value v1.Time) *BillingAccountPaymentArrangementApplyConfiguration {
	b.StartsAt = &value
	return b
}

// WithEndsAt sets the EndsAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndsAt field is set to the value of the last call.
func (b *BillingAccountPaymentArrangementApplyConfiguration) WithEndsAt(value v1.Time) *BillingAccountPaymentArrangementApplyConfiguration {
	b.EndsAt = &value
	return b
}

// WithInvoice sets the Invoice field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Invoice field is set to the value of the last call.
func (b *BillingAccountPaymentArrangementApplyConfiguration) WithInvoice(value *InvoiceArrangementTermsApplyConfiguration) *BillingAccountPaymentArrangementApplyConfiguration {
	b.Invoice = value
	return b
}
