// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingAccountBindingSpecApplyConfiguration represents a declarative configuration of the BillingAccountBindingSpec type for use
// with apply.
//
// BillingAccountBindingSpec defines the desired state of a BillingAccountBinding.
// All fields in this spec are immutable once created.
type BillingAccountBindingSpecApplyConfiguration struct {
	// BillingAccountRef references the billing account to bind.
	BillingAccountRef *BillingAccountRefApplyConfiguration `json:"billingAccountRef,omitempty"`
	// ProjectRef references the project to bind to the billing account.
	ProjectRef *ProjectRefApplyConfiguration `json:"projectRef,omitempty"`
}

// BillingAccountBindingSpecApplyConfiguration constructs a declarative configuration of the BillingAccountBindingSpec type for use with
// apply.
func BillingAccountBindingSpec() *BillingAccountBindingSpecApplyConfiguration {
	return &BillingAccountBindingSpecApplyConfiguration{}
}

// WithBillingAccountRef sets the BillingAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAccountRef field is set to the value of the last call.
func (b *BillingAccountBindingSpecApplyConfiguration) WithBillingAccountRef(value *BillingAccountRefApplyConfiguration) *BillingAccountBindingSpecApplyConfiguration {
	b.BillingAccountRef = value
	return b
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *BillingAccountBindingSpecApplyConfiguration) WithProjectRef(value *ProjectRefApplyConfiguration) *BillingAccountBindingSpecApplyConfiguration {
	b.ProjectRef = value
	return b
}
