// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingAccountRefApplyConfiguration represents a declarative configuration of the BillingAccountRef type for use
// with apply.
//
// BillingAccountRef is a reference to a BillingAccount by name within the
// same namespace.
type BillingAccountRefApplyConfiguration struct {
	// Name is the name of the BillingAccount.
	Name *string `json:"name,omitempty"`
}

// BillingAccountRefApplyConfiguration constructs a declarative configuration of the BillingAccountRef type for use with
// apply.
func BillingAccountRef() *BillingAccountRefApplyConfiguration {
	return &BillingAccountRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BillingAccountRefApplyConfiguration) WithName(value string) *BillingAccountRefApplyConfiguration {
	b.Name = &value
	return b
}
