// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BillingAccountStatusApplyConfiguration represents a declarative configuration of the BillingAccountStatus type for use
// with apply.
//
// BillingAccountStatus defines the observed state of a BillingAccount.
type BillingAccountStatusApplyConfiguration struct {
	// Phase represents the current lifecycle phase of the billing account.
	Phase *apiv1alpha1.BillingAccountPhase `json:"phase,omitempty"`
	// Conditions represent the latest available observations of the billing
	// account's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LinkedProjectsCount is the number of projects currently bound to this
	// billing account.
	LinkedProjectsCount *int32 `json:"linkedProjectsCount,omitempty"`
	// LatestInvoiceRef references the most recently created Invoice for
	// this billing account. Cleared when no invoices exist.
	LatestInvoiceRef *LatestInvoiceRefApplyConfiguration `json:"latestInvoiceRef,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BillingAccountStatusApplyConfiguration constructs a declarative configuration of the BillingAccountStatus type for use with
// apply.
func BillingAccountStatus() *BillingAccountStatusApplyConfiguration {
	return &BillingAccountStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BillingAccountStatusApplyConfiguration) WithPhase(value apiv1alpha1.BillingAccountPhase) *BillingAccountStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BillingAccountStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BillingAccountStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLinkedProjectsCount sets the LinkedProjectsCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LinkedProjectsCount field is set to the value of the last call.
func (b *BillingAccountStatusApplyConfiguration) WithLinkedProjectsCount(value int32) *BillingAccountStatusApplyConfiguration {
	b.LinkedProjectsCount = &value
	return b
}

// WithLatestInvoiceRef sets the LatestInvoiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LatestInvoiceRef field is set to the value of the last call.
func (b *BillingAccountStatusApplyConfiguration) WithLatestInvoiceRef(value *LatestInvoiceRefApplyConfiguration) *BillingAccountStatusApplyConfiguration {
	b.LatestInvoiceRef = value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BillingAccountStatusApplyConfiguration) WithObservedGeneration(value int64) *BillingAccountStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
