// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingContactInfoApplyConfiguration represents a declarative configuration of the BillingContactInfo type for use
// with apply.
//
// BillingContactInfo defines contact details for billing notifications,
// the postal address invoices are issued to, and an optional dedicated
// invoice-recipient email.
type BillingContactInfoApplyConfiguration struct {
	// Email is the primary billing contact email. Receives billing
	// notifications and, when InvoiceEmail is unset, also receives
	// invoices and receipts.
	Email *string `json:"email,omitempty"`
	// Name is the display name of the individual billing contact —
	// the human the platform talks to. Surfaces as the "ATTN:" line
	// on invoices when BusinessName is also set.
	Name *string `json:"name,omitempty"`
	// BusinessName is the legal entity that pays. Optional; populate
	// it for B2B accounts so invoices print the company name as the
	// top header line and the provider Customer record carries the
	// company name rather than the individual contact.
	//
	// When set, the provider controller maps this onto its
	// Customer.name field (e.g. Stripe Customer.name). When unset,
	// Name is used instead.
	BusinessName *string `json:"businessName,omitempty"`
	// InvoiceEmails is the list of recipients that invoices and
	// receipts are sent to. The first entry is the primary recipient;
	// subsequent entries are CC'd. When the list is empty, Email is
	// used as a single primary recipient.
	//
	// Provider support for multiple recipients varies: Stripe
	// Customer.email is single-valued, so the stripe-provider maps
	// the first entry onto it and CC's the rest via its own
	// invoice-sent webhook (when configured). Consumers should treat
	// the entire list as authoritative; the provider handles fan-out.
	//
	// Duplicate entries are rejected. Maximum 10 entries.
	InvoiceEmails []string `json:"invoiceEmails,omitempty"`
	// Address is the postal billing address. Appears on invoices and
	// is surfaced to the configured provider controller (e.g. for
	// tax determination, AVS).
	Address *BillingAddressApplyConfiguration `json:"address,omitempty"`
}

// BillingContactInfoApplyConfiguration constructs a declarative configuration of the BillingContactInfo type for use with
// apply.
func BillingContactInfo() *BillingContactInfoApplyConfiguration {
	return &BillingContactInfoApplyConfiguration{}
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *BillingContactInfoApplyConfiguration) WithEmail(value string) *BillingContactInfoApplyConfiguration {
	b.Email = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BillingContactInfoApplyConfiguration) WithName(value string) *BillingContactInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithBusinessName sets the BusinessName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BusinessName field is set to the value of the last call.
func (b *BillingContactInfoApplyConfiguration) WithBusinessName(value string) *BillingContactInfoApplyConfiguration {
	b.BusinessName = &value
	return b
}

// WithInvoiceEmails adds the given value to the InvoiceEmails field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InvoiceEmails field.
func (b *BillingContactInfoApplyConfiguration) WithInvoiceEmails(values ...string) *BillingContactInfoApplyConfiguration {
	for i := range values {
		b.InvoiceEmails = append(b.InvoiceEmails, values[i])
	}
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *BillingContactInfoApplyConfiguration) WithAddress(value *BillingAddressApplyConfiguration) *BillingContactInfoApplyConfiguration {
	b.Address = value
	return b
}
