// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BillingAccountBindingStatusApplyConfiguration represents a declarative configuration of the BillingAccountBindingStatus type for use
// with apply.
//
// BillingAccountBindingStatus defines the observed state of a BillingAccountBinding.
type BillingAccountBindingStatusApplyConfiguration struct {
	// Phase represents the current lifecycle phase of the binding.
	Phase *apiv1alpha1.BillingAccountBindingPhase `json:"phase,omitempty"`
	// Conditions represent the latest available observations of the binding's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// BillingResponsibility tracks when billing responsibility was established
	// for this binding.
	BillingResponsibility *BillingResponsibilityApplyConfiguration `json:"billingResponsibility,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BillingAccountBindingStatusApplyConfiguration constructs a declarative configuration of the BillingAccountBindingStatus type for use with
// apply.
func BillingAccountBindingStatus() *BillingAccountBindingStatusApplyConfiguration {
	return &BillingAccountBindingStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BillingAccountBindingStatusApplyConfiguration) WithPhase(value apiv1alpha1.BillingAccountBindingPhase) *BillingAccountBindingStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BillingAccountBindingStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BillingAccountBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithBillingResponsibility sets the BillingResponsibility field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingResponsibility field is set to the value of the last call.
func (b *BillingAccountBindingStatusApplyConfiguration) WithBillingResponsibility(value *BillingResponsibilityApplyConfiguration) *BillingAccountBindingStatusApplyConfiguration {
	b.BillingResponsibility = value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BillingAccountBindingStatusApplyConfiguration) WithObservedGeneration(value int64) *BillingAccountBindingStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
