// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BillingResponsibilityApplyConfiguration represents a declarative configuration of the BillingResponsibility type for use
// with apply.
//
// BillingResponsibility tracks when billing responsibility was established.
type BillingResponsibilityApplyConfiguration struct {
	// EstablishedAt is the time when billing responsibility was established.
	EstablishedAt *v1.Time `json:"establishedAt,omitempty"`
	// CurrentAccount is the name of the currently responsible billing account.
	CurrentAccount *string `json:"currentAccount,omitempty"`
}

// BillingResponsibilityApplyConfiguration constructs a declarative configuration of the BillingResponsibility type for use with
// apply.
func BillingResponsibility() *BillingResponsibilityApplyConfiguration {
	return &BillingResponsibilityApplyConfiguration{}
}

// WithEstablishedAt sets the EstablishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstablishedAt field is set to the value of the last call.
func (b *BillingResponsibilityApplyConfiguration) WithEstablishedAt(value v1.Time) *BillingResponsibilityApplyConfiguration {
	b.EstablishedAt = &value
	return b
}

// WithCurrentAccount sets the CurrentAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentAccount field is set to the value of the last call.
func (b *BillingResponsibilityApplyConfiguration) WithCurrentAccount(value string) *BillingResponsibilityApplyConfiguration {
	b.CurrentAccount = &value
	return b
}
