// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingEntitlementSpecApplyConfiguration represents a declarative configuration of the BillingEntitlementSpec type for use
// with apply.
//
// BillingEntitlementSpec defines the desired state of a BillingEntitlement.
//
// Exactly one active BillingEntitlement exists per billing account. It
// binds the account to a published Offer. Distinct from the per-project
// ServiceEntitlement in service-catalog.
type BillingEntitlementSpecApplyConfiguration struct {
	// BillingAccountRef references the BillingAccount in the same
	// namespace.
	BillingAccountRef *BillingAccountRefApplyConfiguration `json:"billingAccountRef,omitempty"`
	// OfferRef references a cluster-scoped published (GA) Offer.
	OfferRef *OfferReferenceApplyConfiguration `json:"offerRef,omitempty"`
}

// BillingEntitlementSpecApplyConfiguration constructs a declarative configuration of the BillingEntitlementSpec type for use with
// apply.
func BillingEntitlementSpec() *BillingEntitlementSpecApplyConfiguration {
	return &BillingEntitlementSpecApplyConfiguration{}
}

// WithBillingAccountRef sets the BillingAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAccountRef field is set to the value of the last call.
func (b *BillingEntitlementSpecApplyConfiguration) WithBillingAccountRef(value *BillingAccountRefApplyConfiguration) *BillingEntitlementSpecApplyConfiguration {
	b.BillingAccountRef = value
	return b
}

// WithOfferRef sets the OfferRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OfferRef field is set to the value of the last call.
func (b *BillingEntitlementSpecApplyConfiguration) WithOfferRef(value *OfferReferenceApplyConfiguration) *BillingEntitlementSpecApplyConfiguration {
	b.OfferRef = value
	return b
}
