// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BillingArrangementStatusApplyConfiguration represents a declarative configuration of the BillingArrangementStatus type for use
// with apply.
//
// BillingArrangementStatus defines the observed state of a
// BillingArrangement.
type BillingArrangementStatusApplyConfiguration struct {
	// Phase is where the arrangement sits in its validity window.
	Phase *apiv1alpha1.BillingArrangementPhase `json:"phase,omitempty"`
	// Conditions represent the latest available observations of the
	// arrangement's state. See BillingArrangementConditionActive.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the
	// controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BillingArrangementStatusApplyConfiguration constructs a declarative configuration of the BillingArrangementStatus type for use with
// apply.
func BillingArrangementStatus() *BillingArrangementStatusApplyConfiguration {
	return &BillingArrangementStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BillingArrangementStatusApplyConfiguration) WithPhase(value apiv1alpha1.BillingArrangementPhase) *BillingArrangementStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BillingArrangementStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BillingArrangementStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BillingArrangementStatusApplyConfiguration) WithObservedGeneration(value int64) *BillingArrangementStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
