// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BillingAccountSpecApplyConfiguration represents a declarative configuration of the BillingAccountSpec type for use
// with apply.
//
// BillingAccountSpec defines the desired state of a BillingAccount.
type BillingAccountSpecApplyConfiguration struct {
	// CurrencyCode is the ISO 4217 currency code for this billing account.
	// This field is immutable once the account transitions past Provisioning phase.
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// PaymentTerms defines the invoicing schedule for this billing account.
	PaymentTerms *PaymentTermsApplyConfiguration `json:"paymentTerms,omitempty"`
	// ContactInfo describes the billing contact and the postal
	// address invoices are issued to.
	ContactInfo *BillingContactInfoApplyConfiguration `json:"contactInfo,omitempty"`
	// TaxIDs are the tax registrations attached to this account. An
	// account can carry multiple entries (e.g. an organisation
	// registered for both GB VAT and EU VAT).
	TaxIDs []TaxIDApplyConfiguration `json:"taxIds,omitempty"`
	// DefaultPaymentMethodRef references the PaymentMethod to use by
	// default for charge processing. The referenced PaymentMethod must
	// reside in the same namespace and be in the Active phase.
	DefaultPaymentMethodRef *DefaultPaymentMethodRefApplyConfiguration `json:"defaultPaymentMethodRef,omitempty"`
}

// BillingAccountSpecApplyConfiguration constructs a declarative configuration of the BillingAccountSpec type for use with
// apply.
func BillingAccountSpec() *BillingAccountSpecApplyConfiguration {
	return &BillingAccountSpecApplyConfiguration{}
}

// WithCurrencyCode sets the CurrencyCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrencyCode field is set to the value of the last call.
func (b *BillingAccountSpecApplyConfiguration) WithCurrencyCode(value string) *BillingAccountSpecApplyConfiguration {
	b.CurrencyCode = &value
	return b
}

// WithPaymentTerms sets the PaymentTerms field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PaymentTerms field is set to the value of the last call.
func (b *BillingAccountSpecApplyConfiguration) WithPaymentTerms(value *PaymentTermsApplyConfiguration) *BillingAccountSpecApplyConfiguration {
	b.PaymentTerms = value
	return b
}

// WithContactInfo sets the ContactInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContactInfo field is set to the value of the last call.
func (b *BillingAccountSpecApplyConfiguration) WithContactInfo(value *BillingContactInfoApplyConfiguration) *BillingAccountSpecApplyConfiguration {
	b.ContactInfo = value
	return b
}

// WithTaxIDs adds the given value to the TaxIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TaxIDs field.
func (b *BillingAccountSpecApplyConfiguration) WithTaxIDs(values ...*TaxIDApplyConfiguration) *BillingAccountSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaxIDs")
		}
		b.TaxIDs = append(b.TaxIDs, *values[i])
	}
	return b
}

// WithDefaultPaymentMethodRef sets the DefaultPaymentMethodRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultPaymentMethodRef field is set to the value of the last call.
func (b *BillingAccountSpecApplyConfiguration) WithDefaultPaymentMethodRef(value *DefaultPaymentMethodRefApplyConfiguration) *BillingAccountSpecApplyConfiguration {
	b.DefaultPaymentMethodRef = value
	return b
}
