// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BillingArrangementSpecApplyConfiguration represents a declarative configuration of the BillingArrangementSpec type for use
// with apply.
//
// BillingArrangementSpec defines the desired state of a BillingArrangement.
type BillingArrangementSpecApplyConfiguration struct {
	// BillingAccountRef references the BillingAccount in the same
	// namespace that these terms apply to. Immutable.
	BillingAccountRef *BillingAccountRefApplyConfiguration `json:"billingAccountRef,omitempty"`
	// Type selects how the account is billed. Immutable; to change type,
	// end this arrangement and create a new one.
	Type *apiv1alpha1.BillingArrangementType `json:"type,omitempty"`
	// Invoice carries the invoice terms. Required when type is Invoice.
	Invoice *InvoiceArrangementTermsApplyConfiguration `json:"invoice,omitempty"`
	// StartsAt is when the arrangement takes effect. Defaulted to the
	// time of creation when omitted.
	StartsAt *v1.Time `json:"startsAt,omitempty"`
	// EndsAt is when the arrangement stops applying. Leave unset for terms
	// with no fixed end. Staff end terms early by setting this to the
	// current time, which keeps the record for history.
	EndsAt *v1.Time `json:"endsAt,omitempty"`
	// Reason records why staff granted these terms (for example "Signed
	// MSA, sales call 2026-10-01"). Internal: never shown to customers.
	Reason *string `json:"reason,omitempty"`
}

// BillingArrangementSpecApplyConfiguration constructs a declarative configuration of the BillingArrangementSpec type for use with
// apply.
func BillingArrangementSpec() *BillingArrangementSpecApplyConfiguration {
	return &BillingArrangementSpecApplyConfiguration{}
}

// WithBillingAccountRef sets the BillingAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAccountRef field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithBillingAccountRef(value *BillingAccountRefApplyConfiguration) *BillingArrangementSpecApplyConfiguration {
	b.BillingAccountRef = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithType(value apiv1alpha1.BillingArrangementType) *BillingArrangementSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithInvoice sets the Invoice field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Invoice field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithInvoice(value *InvoiceArrangementTermsApplyConfiguration) *BillingArrangementSpecApplyConfiguration {
	b.Invoice = value
	return b
}

// WithStartsAt sets the StartsAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartsAt field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithStartsAt(value v1.Time) *BillingArrangementSpecApplyConfiguration {
	b.StartsAt = &value
	return b
}

// WithEndsAt sets the EndsAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndsAt field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithEndsAt(value v1.Time) *BillingArrangementSpecApplyConfiguration {
	b.EndsAt = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *BillingArrangementSpecApplyConfiguration) WithReason(value string) *BillingArrangementSpecApplyConfiguration {
	b.Reason = &value
	return b
}
