// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CardBillingAddressApplyConfiguration represents a declarative configuration of the CardBillingAddress type for use
// with apply.
//
// CardBillingAddress is the cardholder address attached to a confirmed
// payment instrument. Subset of BillingAddress — no name fields
// because cardholder name is recorded separately by the provider
// alongside the rest of the billing_details / equivalent payload.
type CardBillingAddressApplyConfiguration struct {
	// Country is the ISO 3166-1 alpha-2 country code of the
	// cardholder address.
	Country *string `json:"country,omitempty"`
	// Line1 is the first line of the street address.
	Line1 *string `json:"line1,omitempty"`
	// Line2 is the second line of the street address.
	Line2 *string `json:"line2,omitempty"`
	// City is the locality.
	City *string `json:"city,omitempty"`
	// Region is the state, province, or county.
	Region *string `json:"region,omitempty"`
	// PostalCode is the post / zip code.
	PostalCode *string `json:"postalCode,omitempty"`
}

// CardBillingAddressApplyConfiguration constructs a declarative configuration of the CardBillingAddress type for use with
// apply.
func CardBillingAddress() *CardBillingAddressApplyConfiguration {
	return &CardBillingAddressApplyConfiguration{}
}

// WithCountry sets the Country field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Country field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithCountry(value string) *CardBillingAddressApplyConfiguration {
	b.Country = &value
	return b
}

// WithLine1 sets the Line1 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Line1 field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithLine1(value string) *CardBillingAddressApplyConfiguration {
	b.Line1 = &value
	return b
}

// WithLine2 sets the Line2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Line2 field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithLine2(value string) *CardBillingAddressApplyConfiguration {
	b.Line2 = &value
	return b
}

// WithCity sets the City field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the City field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithCity(value string) *CardBillingAddressApplyConfiguration {
	b.City = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithRegion(value string) *CardBillingAddressApplyConfiguration {
	b.Region = &value
	return b
}

// WithPostalCode sets the PostalCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostalCode field is set to the value of the last call.
func (b *CardBillingAddressApplyConfiguration) WithPostalCode(value string) *CardBillingAddressApplyConfiguration {
	b.PostalCode = &value
	return b
}
