// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CatalogStatusApplyConfiguration represents a declarative configuration of the CatalogStatus type for use
// with apply.
//
// CatalogStatus is the shared status shape for catalog resources.
type CatalogStatusApplyConfiguration struct {
	// PublishedAt is the time at which the controller first observed the
	// resource in the Published phase.
	PublishedAt *v1.Time `json:"publishedAt,omitempty"`
	// Conditions represent the latest available observations of the resource's state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// CatalogStatusApplyConfiguration constructs a declarative configuration of the CatalogStatus type for use with
// apply.
func CatalogStatus() *CatalogStatusApplyConfiguration {
	return &CatalogStatusApplyConfiguration{}
}

// WithPublishedAt sets the PublishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishedAt field is set to the value of the last call.
func (b *CatalogStatusApplyConfiguration) WithPublishedAt(value v1.Time) *CatalogStatusApplyConfiguration {
	b.PublishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CatalogStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *CatalogStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *CatalogStatusApplyConfiguration) WithObservedGeneration(value int64) *CatalogStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
