// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DefaultPaymentMethodRefApplyConfiguration represents a declarative configuration of the DefaultPaymentMethodRef type for use
// with apply.
//
// DefaultPaymentMethodRef references a PaymentMethod in the same namespace
// as the BillingAccount.
type DefaultPaymentMethodRefApplyConfiguration struct {
	// Name is the name of the PaymentMethod.
	Name *string `json:"name,omitempty"`
}

// DefaultPaymentMethodRefApplyConfiguration constructs a declarative configuration of the DefaultPaymentMethodRef type for use with
// apply.
func DefaultPaymentMethodRef() *DefaultPaymentMethodRefApplyConfiguration {
	return &DefaultPaymentMethodRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DefaultPaymentMethodRefApplyConfiguration) WithName(value string) *DefaultPaymentMethodRefApplyConfiguration {
	b.Name = &value
	return b
}
