// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DimensionMatchApplyConfiguration represents a declarative configuration of the DimensionMatch type for use
// with apply.
//
// DimensionMatch selects a rate by a single MeterDefinition dimension
// value. Multi-dimension matches are deferred.
type DimensionMatchApplyConfiguration struct {
	// Dimension is the label key declared on the monitored resource type
	// (e.g. "tier", "region", "model").
	Dimension *string `json:"dimension,omitempty"`
	// Value is the dimension value this rate applies to.
	Value *string `json:"value,omitempty"`
}

// DimensionMatchApplyConfiguration constructs a declarative configuration of the DimensionMatch type for use with
// apply.
func DimensionMatch() *DimensionMatchApplyConfiguration {
	return &DimensionMatchApplyConfiguration{}
}

// WithDimension sets the Dimension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dimension field is set to the value of the last call.
func (b *DimensionMatchApplyConfiguration) WithDimension(value string) *DimensionMatchApplyConfiguration {
	b.Dimension = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *DimensionMatchApplyConfiguration) WithValue(value string) *DimensionMatchApplyConfiguration {
	b.Value = &value
	return b
}
