// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InvoiceArrangementTermsApplyConfiguration represents a declarative configuration of the InvoiceArrangementTerms type for use
// with apply.
//
// InvoiceArrangementTerms are the terms an invoice-billed account is held
// to. They're published on BillingAccount status for finance and, later,
// the automated invoicing pipeline.
type InvoiceArrangementTermsApplyConfiguration struct {
	// NetDays is the number of days after the invoice date that payment
	// is due.
	NetDays *int32 `json:"netDays,omitempty"`
	// CreditLimit is the maximum spend per billing cycle, as a decimal
	// string in the billing account's currency (e.g. "10000"). Staff are
	// alerted as the account nears it; it is not a hard cap.
	CreditLimit *string `json:"creditLimit,omitempty"`
	// AccountsPayableEmail receives invoices in addition to the billing
	// contact. When unset, invoices go to the billing contact only.
	AccountsPayableEmail *string `json:"accountsPayableEmail,omitempty"`
	// PurchaseOrderNumber is printed on invoices.
	PurchaseOrderNumber *string `json:"purchaseOrderNumber,omitempty"`
	// AgreementReference identifies a signed MSA or order form, when one
	// exists. Without one, our standard terms of service apply.
	AgreementReference *string `json:"agreementReference,omitempty"`
}

// InvoiceArrangementTermsApplyConfiguration constructs a declarative configuration of the InvoiceArrangementTerms type for use with
// apply.
func InvoiceArrangementTerms() *InvoiceArrangementTermsApplyConfiguration {
	return &InvoiceArrangementTermsApplyConfiguration{}
}

// WithNetDays sets the NetDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetDays field is set to the value of the last call.
func (b *InvoiceArrangementTermsApplyConfiguration) WithNetDays(value int32) *InvoiceArrangementTermsApplyConfiguration {
	b.NetDays = &value
	return b
}

// WithCreditLimit sets the CreditLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreditLimit field is set to the value of the last call.
func (b *InvoiceArrangementTermsApplyConfiguration) WithCreditLimit(value string) *InvoiceArrangementTermsApplyConfiguration {
	b.CreditLimit = &value
	return b
}

// WithAccountsPayableEmail sets the AccountsPayableEmail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountsPayableEmail field is set to the value of the last call.
func (b *InvoiceArrangementTermsApplyConfiguration) WithAccountsPayableEmail(value string) *InvoiceArrangementTermsApplyConfiguration {
	b.AccountsPayableEmail = &value
	return b
}

// WithPurchaseOrderNumber sets the PurchaseOrderNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PurchaseOrderNumber field is set to the value of the last call.
func (b *InvoiceArrangementTermsApplyConfiguration) WithPurchaseOrderNumber(value string) *InvoiceArrangementTermsApplyConfiguration {
	b.PurchaseOrderNumber = &value
	return b
}

// WithAgreementReference sets the AgreementReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgreementReference field is set to the value of the last call.
func (b *InvoiceArrangementTermsApplyConfiguration) WithAgreementReference(value string) *InvoiceArrangementTermsApplyConfiguration {
	b.AgreementReference = &value
	return b
}
