// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InvoiceStatusApplyConfiguration represents a declarative configuration of the InvoiceStatus type for use
// with apply.
//
// InvoiceStatus defines the observed state of an Invoice. Populated
// exclusively by the invoicing provider.
type InvoiceStatusApplyConfiguration struct {
	// Phase represents the current payment lifecycle phase.
	Phase *apiv1alpha1.InvoicePhase `json:"phase,omitempty"`
	// CurrencyCode is the ISO 4217 currency code for the invoice totals.
	// Must match BillingAccount.spec.currencyCode; providers that detect
	// a mismatch surface Ready=False with reason CurrencyMismatch.
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// Total is the invoice total as computed by the provider, expressed
	// as a decimal string (e.g. "482.19").
	Total *string `json:"total,omitempty"`
	// AmountPaid is the amount collected so far, as a decimal string.
	AmountPaid *string `json:"amountPaid,omitempty"`
	// AmountDue is the remaining balance. Provider-authoritative — not
	// derived client-side from total and amountPaid.
	AmountDue *string `json:"amountDue,omitempty"`
	// DueDate is when payment is due.
	DueDate *v1.Time `json:"dueDate,omitempty"`
	// PaidAt is set once amountDue reaches zero.
	PaidAt *v1.Time `json:"paidAt,omitempty"`
	// DocumentUri is a provider-hosted link to the human-readable
	// invoice document (PDF or HTML).
	DocumentURI *string `json:"documentUri,omitempty"`
	// Conditions represent the latest available observations of the
	// invoice's state. See InvoiceConditionReady.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the
	// reconciling provider controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// InvoiceStatusApplyConfiguration constructs a declarative configuration of the InvoiceStatus type for use with
// apply.
func InvoiceStatus() *InvoiceStatusApplyConfiguration {
	return &InvoiceStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithPhase(value apiv1alpha1.InvoicePhase) *InvoiceStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithCurrencyCode sets the CurrencyCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrencyCode field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithCurrencyCode(value string) *InvoiceStatusApplyConfiguration {
	b.CurrencyCode = &value
	return b
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithTotal(value string) *InvoiceStatusApplyConfiguration {
	b.Total = &value
	return b
}

// WithAmountPaid sets the AmountPaid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AmountPaid field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithAmountPaid(value string) *InvoiceStatusApplyConfiguration {
	b.AmountPaid = &value
	return b
}

// WithAmountDue sets the AmountDue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AmountDue field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithAmountDue(value string) *InvoiceStatusApplyConfiguration {
	b.AmountDue = &value
	return b
}

// WithDueDate sets the DueDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DueDate field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithDueDate(value v1.Time) *InvoiceStatusApplyConfiguration {
	b.DueDate = &value
	return b
}

// WithPaidAt sets the PaidAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PaidAt field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithPaidAt(value v1.Time) *InvoiceStatusApplyConfiguration {
	b.PaidAt = &value
	return b
}

// WithDocumentURI sets the DocumentURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DocumentURI field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithDocumentURI(value string) *InvoiceStatusApplyConfiguration {
	b.DocumentURI = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InvoiceStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *InvoiceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *InvoiceStatusApplyConfiguration) WithObservedGeneration(value int64) *InvoiceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
