// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InvoicePeriodApplyConfiguration represents a declarative configuration of the InvoicePeriod type for use
// with apply.
//
// InvoicePeriod is the closed billing window covered by an Invoice.
type InvoicePeriodApplyConfiguration struct {
	// Start is the inclusive start of the billing period.
	Start *v1.Time `json:"start,omitempty"`
	// End is the inclusive end of the billing period.
	End *v1.Time `json:"end,omitempty"`
}

// InvoicePeriodApplyConfiguration constructs a declarative configuration of the InvoicePeriod type for use with
// apply.
func InvoicePeriod() *InvoicePeriodApplyConfiguration {
	return &InvoicePeriodApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *InvoicePeriodApplyConfiguration) WithStart(value v1.Time) *InvoicePeriodApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *InvoicePeriodApplyConfiguration) WithEnd(value v1.Time) *InvoicePeriodApplyConfiguration {
	b.End = &value
	return b
}
