// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InvoiceSpecApplyConfiguration represents a declarative configuration of the InvoiceSpec type for use
// with apply.
//
// InvoiceSpec defines the desired state of an Invoice.
//
// Invoice is created and updated exclusively by an invoicing provider —
// never by a consumer or the portal. Spec fields are immutable once set.
type InvoiceSpecApplyConfiguration struct {
	// BillingAccountRef references the BillingAccount this invoice
	// belongs to. The BillingAccount must reside in the same namespace.
	// Immutable once set.
	BillingAccountRef *BillingAccountRefApplyConfiguration `json:"billingAccountRef,omitempty"`
	// Period is the billing period this invoice covers. Immutable once set.
	Period *InvoicePeriodApplyConfiguration `json:"period,omitempty"`
}

// InvoiceSpecApplyConfiguration constructs a declarative configuration of the InvoiceSpec type for use with
// apply.
func InvoiceSpec() *InvoiceSpecApplyConfiguration {
	return &InvoiceSpecApplyConfiguration{}
}

// WithBillingAccountRef sets the BillingAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAccountRef field is set to the value of the last call.
func (b *InvoiceSpecApplyConfiguration) WithBillingAccountRef(value *BillingAccountRefApplyConfiguration) *InvoiceSpecApplyConfiguration {
	b.BillingAccountRef = value
	return b
}

// WithPeriod sets the Period field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Period field is set to the value of the last call.
func (b *InvoiceSpecApplyConfiguration) WithPeriod(value *InvoicePeriodApplyConfiguration) *InvoiceSpecApplyConfiguration {
	b.Period = value
	return b
}
