// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LatestInvoiceRefApplyConfiguration represents a declarative configuration of the LatestInvoiceRef type for use
// with apply.
//
// LatestInvoiceRef references an Invoice in the same namespace as the
// BillingAccount. Set by the billing service controller to the most
// recently created Invoice for the account.
type LatestInvoiceRefApplyConfiguration struct {
	// Name is the name of the Invoice.
	Name *string `json:"name,omitempty"`
}

// LatestInvoiceRefApplyConfiguration constructs a declarative configuration of the LatestInvoiceRef type for use with
// apply.
func LatestInvoiceRef() *LatestInvoiceRefApplyConfiguration {
	return &LatestInvoiceRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LatestInvoiceRefApplyConfiguration) WithName(value string) *LatestInvoiceRefApplyConfiguration {
	b.Name = &value
	return b
}
