// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MeterBillingApplyConfiguration represents a declarative configuration of the MeterBilling type for use
// with apply.
//
// MeterBilling describes the commercial framing of a meter. Field names
// borrow from the FOCUS specification for clean exports.
type MeterBillingApplyConfiguration struct {
	// ConsumedUnit is the UCUM unit in which usage is measured (e.g.
	// "s"). Typically matches measurement.unit; may diverge when the
	// emitted telemetry is pre-converted. Equality with measurement.unit is
	// not enforced.
	ConsumedUnit *string `json:"consumedUnit,omitempty"`
	// PricingUnit is the UCUM unit pricing quotes against (e.g. "h").
	// May differ from ConsumedUnit; the pricing engine handles the
	// conversion.
	PricingUnit *string `json:"pricingUnit,omitempty"`
}

// MeterBillingApplyConfiguration constructs a declarative configuration of the MeterBilling type for use with
// apply.
func MeterBilling() *MeterBillingApplyConfiguration {
	return &MeterBillingApplyConfiguration{}
}

// WithConsumedUnit sets the ConsumedUnit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumedUnit field is set to the value of the last call.
func (b *MeterBillingApplyConfiguration) WithConsumedUnit(value string) *MeterBillingApplyConfiguration {
	b.ConsumedUnit = &value
	return b
}

// WithPricingUnit sets the PricingUnit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PricingUnit field is set to the value of the last call.
func (b *MeterBillingApplyConfiguration) WithPricingUnit(value string) *MeterBillingApplyConfiguration {
	b.PricingUnit = &value
	return b
}
