// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MeterDefinitionStatusApplyConfiguration represents a declarative configuration of the MeterDefinitionStatus type for use
// with apply.
//
// MeterDefinitionStatus defines the observed state of a MeterDefinition.
type MeterDefinitionStatusApplyConfiguration struct {
	// CatalogStatus embeds the shared catalog lifecycle fields
	// (publishedAt, conditions, observedGeneration). Phase lives on
	// spec; status mirrors it via the Published condition.
	CatalogStatusApplyConfiguration `json:",inline"`
	// SystemDimensions lists the dimension keys injected by the billing
	// pipeline on every valid event, in addition to those declared in
	// spec.measurement.dimensions. Providers must configure these alongside
	// spec.measurement.dimensions when setting up meters in downstream systems.
	SystemDimensions []string `json:"systemDimensions,omitempty"`
}

// MeterDefinitionStatusApplyConfiguration constructs a declarative configuration of the MeterDefinitionStatus type for use with
// apply.
func MeterDefinitionStatus() *MeterDefinitionStatusApplyConfiguration {
	return &MeterDefinitionStatusApplyConfiguration{}
}

// WithPublishedAt sets the PublishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishedAt field is set to the value of the last call.
func (b *MeterDefinitionStatusApplyConfiguration) WithPublishedAt(value v1.Time) *MeterDefinitionStatusApplyConfiguration {
	b.CatalogStatusApplyConfiguration.PublishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MeterDefinitionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MeterDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.CatalogStatusApplyConfiguration.Conditions = append(b.CatalogStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MeterDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *MeterDefinitionStatusApplyConfiguration {
	b.CatalogStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithSystemDimensions adds the given value to the SystemDimensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SystemDimensions field.
func (b *MeterDefinitionStatusApplyConfiguration) WithSystemDimensions(values ...string) *MeterDefinitionStatusApplyConfiguration {
	for i := range values {
		b.SystemDimensions = append(b.SystemDimensions, values[i])
	}
	return b
}
