// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// MeterDefinitionSpecApplyConfiguration represents a declarative configuration of the MeterDefinitionSpec type for use
// with apply.
//
// MeterDefinitionSpec defines the desired state of a MeterDefinition.
//
// The spec is organized into three cohesive blocks: identity (who/what
// this is), measurement (how the signal is captured and aggregated),
// and billing (how it crosses into commerce). Core fields (meterName,
// measurement.aggregation, measurement.unit) are immutable once created;
// a breaking change ships as a new MeterDefinition with a versioned meterName.
//
// spec.phase is the provider-declared lifecycle intent: Draft ->
// Published -> Deprecated -> Retired. The controller mirrors that
// intent via conditions; it does not transition the phase itself.
//
// Ownership is expressed via labels (e.g. app.kubernetes.io/managed-by)
// rather than a spec.owner field.
type MeterDefinitionSpecApplyConfiguration struct {
	// MeterName is the canonical, user-facing identifier for this
	// meter. It is the cross-system join key used by invoices, rate
	// cards, marketplace listings, and FOCUS exports. Typically a
	// reverse-DNS path (e.g.
	// "compute.miloapis.com/instance/cpu-seconds"). Immutable.
	MeterName *string `json:"meterName,omitempty"`
	// Phase is the provider-declared lifecycle state of this meter.
	// Allowed transitions are forward-only:
	// Draft -> Published -> Deprecated -> Retired.
	Phase *apiv1alpha1.Phase `json:"phase,omitempty"`
	// DisplayName is a human-readable name surfaced in portals and on
	// invoices alongside the canonical meterName.
	DisplayName *string `json:"displayName,omitempty"`
	// Description is a plain-English explanation of what the meter
	// measures. Editable over the meter's lifetime.
	Description *string `json:"description,omitempty"`
	// Measurement describes how the signal is captured and aggregated.
	Measurement *MeterMeasurementApplyConfiguration `json:"measurement,omitempty"`
	// Billing describes how the meter crosses into commerce. Carries no
	// rates, currencies, or tiers -- those live in the pricing engine.
	Billing *MeterBillingApplyConfiguration `json:"billing,omitempty"`
	// MonitoredResourceTypes names the billing.miloapis.com/MonitoredResourceType
	// instances whose usage events are counted by this meter. Follows
	// Google's MetricDescriptor.monitored_resource_types pattern: each
	// entry identifies a resource type that emits samples this meter
	// aggregates.
	MonitoredResourceTypes []string `json:"monitoredResourceTypes,omitempty"`
}

// MeterDefinitionSpecApplyConfiguration constructs a declarative configuration of the MeterDefinitionSpec type for use with
// apply.
func MeterDefinitionSpec() *MeterDefinitionSpecApplyConfiguration {
	return &MeterDefinitionSpecApplyConfiguration{}
}

// WithMeterName sets the MeterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeterName field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithMeterName(value string) *MeterDefinitionSpecApplyConfiguration {
	b.MeterName = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithPhase(value apiv1alpha1.Phase) *MeterDefinitionSpecApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithDisplayName(value string) *MeterDefinitionSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithDescription(value string) *MeterDefinitionSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithMeasurement sets the Measurement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Measurement field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithMeasurement(value *MeterMeasurementApplyConfiguration) *MeterDefinitionSpecApplyConfiguration {
	b.Measurement = value
	return b
}

// WithBilling sets the Billing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Billing field is set to the value of the last call.
func (b *MeterDefinitionSpecApplyConfiguration) WithBilling(value *MeterBillingApplyConfiguration) *MeterDefinitionSpecApplyConfiguration {
	b.Billing = value
	return b
}

// WithMonitoredResourceTypes adds the given value to the MonitoredResourceTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MonitoredResourceTypes field.
func (b *MeterDefinitionSpecApplyConfiguration) WithMonitoredResourceTypes(values ...string) *MeterDefinitionSpecApplyConfiguration {
	for i := range values {
		b.MonitoredResourceTypes = append(b.MonitoredResourceTypes, values[i])
	}
	return b
}
