// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// MeterMeasurementApplyConfiguration represents a declarative configuration of the MeterMeasurement type for use
// with apply.
//
// MeterMeasurement describes how a meter's signal is captured.
type MeterMeasurementApplyConfiguration struct {
	// Aggregation is the function applied to samples over a billing
	// period. Single source of truth for how usage rolls up. Immutable.
	Aggregation *apiv1alpha1.MeterAggregation `json:"aggregation,omitempty"`
	// Unit is a UCUM (https://ucum.org/ucum) string describing what the
	// meter measures (e.g. "s", "By", "{request}", "GBy.h"). Immutable.
	Unit *string `json:"unit,omitempty"`
	// Dimensions is an ordered list of attribute keys that downstream
	// systems may group by (e.g. "region", "tier", "resource.type").
	// Adding a dimension is additive; removing one is a breaking change
	// and must ship as a new meter.
	Dimensions []string `json:"dimensions,omitempty"`
}

// MeterMeasurementApplyConfiguration constructs a declarative configuration of the MeterMeasurement type for use with
// apply.
func MeterMeasurement() *MeterMeasurementApplyConfiguration {
	return &MeterMeasurementApplyConfiguration{}
}

// WithAggregation sets the Aggregation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggregation field is set to the value of the last call.
func (b *MeterMeasurementApplyConfiguration) WithAggregation(value apiv1alpha1.MeterAggregation) *MeterMeasurementApplyConfiguration {
	b.Aggregation = &value
	return b
}

// WithUnit sets the Unit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unit field is set to the value of the last call.
func (b *MeterMeasurementApplyConfiguration) WithUnit(value string) *MeterMeasurementApplyConfiguration {
	b.Unit = &value
	return b
}

// WithDimensions adds the given value to the Dimensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Dimensions field.
func (b *MeterMeasurementApplyConfiguration) WithDimensions(values ...string) *MeterMeasurementApplyConfiguration {
	for i := range values {
		b.Dimensions = append(b.Dimensions, values[i])
	}
	return b
}
