// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// MonitoredResourceTypeSpecApplyConfiguration represents a declarative configuration of the MonitoredResourceTypeSpec type for use
// with apply.
//
// MonitoredResourceTypeSpec defines the desired state of a
// MonitoredResourceType.
//
// A MonitoredResourceType declares which Kubernetes Kinds are billable
// or otherwise monitored by the platform, and the closed set of
// descriptive labels that usage events against that Kind may carry.
//
// Core fields (resourceTypeName, gvk.group, gvk.kind) are immutable once
// created; a breaking change ships as a new MonitoredResourceType with a
// new canonical name.
//
// spec.phase is the provider-declared lifecycle intent: Draft ->
// Published -> Deprecated -> Retired. The controller mirrors that
// intent via conditions; it does not transition the phase itself.
//
// Ownership is expressed via labels rather than a spec.owner field.
type MonitoredResourceTypeSpecApplyConfiguration struct {
	// ResourceTypeName is the canonical, user-facing identifier for
	// this monitored resource type. It typically combines the owning
	// service's reverse-DNS name with the Kubernetes Kind (e.g.
	// "compute.miloapis.com/Instance") and is the stable identifier
	// used by portal drill-downs, FinOps exports, and billing events.
	// Immutable.
	ResourceTypeName *string `json:"resourceTypeName,omitempty"`
	// Phase is the provider-declared lifecycle state of this
	// monitored resource type. Allowed transitions are forward-only:
	// Draft -> Published -> Deprecated -> Retired.
	Phase *apiv1alpha1.Phase `json:"phase,omitempty"`
	// DisplayName is a human-readable name surfaced in portals and
	// dashboards alongside the canonical resourceTypeName. Editable
	// over the type's lifetime.
	DisplayName *string `json:"displayName,omitempty"`
	// Description is a plain-English explanation of what the resource
	// type represents. Editable over the type's lifetime.
	Description *string `json:"description,omitempty"`
	// GVK pins the resource type to a Kubernetes Kind. Version is
	// deliberately omitted: billability is a property of the Kind, not
	// of a specific API version.
	GVK *MonitoredResourceTypeGVKApplyConfiguration `json:"gvk,omitempty"`
	// Labels is the closed set of descriptive labels that usage events
	// against this resource type are permitted to carry. Events whose
	// labels are not in this set are rejected at the edge. Adding a new
	// optional label is additive; adding a required label or removing
	// any declared label is a breaking change.
	Labels []MonitoredResourceLabelApplyConfiguration `json:"labels,omitempty"`
}

// MonitoredResourceTypeSpecApplyConfiguration constructs a declarative configuration of the MonitoredResourceTypeSpec type for use with
// apply.
func MonitoredResourceTypeSpec() *MonitoredResourceTypeSpecApplyConfiguration {
	return &MonitoredResourceTypeSpecApplyConfiguration{}
}

// WithResourceTypeName sets the ResourceTypeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceTypeName field is set to the value of the last call.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithResourceTypeName(value string) *MonitoredResourceTypeSpecApplyConfiguration {
	b.ResourceTypeName = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithPhase(value apiv1alpha1.Phase) *MonitoredResourceTypeSpecApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithDisplayName(value string) *MonitoredResourceTypeSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithDescription(value string) *MonitoredResourceTypeSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithGVK sets the GVK field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GVK field is set to the value of the last call.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithGVK(value *MonitoredResourceTypeGVKApplyConfiguration) *MonitoredResourceTypeSpecApplyConfiguration {
	b.GVK = value
	return b
}

// WithLabels adds the given value to the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Labels field.
func (b *MonitoredResourceTypeSpecApplyConfiguration) WithLabels(values ...*MonitoredResourceLabelApplyConfiguration) *MonitoredResourceTypeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLabels")
		}
		b.Labels = append(b.Labels, *values[i])
	}
	return b
}
