// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MonitoredResourceLabelApplyConfiguration represents a declarative configuration of the MonitoredResourceLabel type for use
// with apply.
//
// MonitoredResourceLabel declares a single descriptive label that usage
// events against the resource type may carry. Labels form a closed set:
// events bearing any label not declared here are rejected before they
// reach the audit log.
type MonitoredResourceLabelApplyConfiguration struct {
	// Name is the label key as it will appear on usage events (e.g.
	// "region", "zone", "tier"). It is the map key for this list.
	Name *string `json:"name,omitempty"`
	// Required indicates whether every usage event against this
	// resource type must carry this label. Defaults to false
	// (optional).
	Required *bool `json:"required,omitempty"`
	// Description is a plain-English explanation of what the label
	// conveys. Editable over the resource type's lifetime.
	Description *string `json:"description,omitempty"`
	// AllowedValues, when non-empty, constrains the label to a fixed
	// vocabulary. Events carrying a value outside this set are rejected.
	AllowedValues []string `json:"allowedValues,omitempty"`
}

// MonitoredResourceLabelApplyConfiguration constructs a declarative configuration of the MonitoredResourceLabel type for use with
// apply.
func MonitoredResourceLabel() *MonitoredResourceLabelApplyConfiguration {
	return &MonitoredResourceLabelApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MonitoredResourceLabelApplyConfiguration) WithName(value string) *MonitoredResourceLabelApplyConfiguration {
	b.Name = &value
	return b
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *MonitoredResourceLabelApplyConfiguration) WithRequired(value bool) *MonitoredResourceLabelApplyConfiguration {
	b.Required = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *MonitoredResourceLabelApplyConfiguration) WithDescription(value string) *MonitoredResourceLabelApplyConfiguration {
	b.Description = &value
	return b
}

// WithAllowedValues adds the given value to the AllowedValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedValues field.
func (b *MonitoredResourceLabelApplyConfiguration) WithAllowedValues(values ...string) *MonitoredResourceLabelApplyConfiguration {
	for i := range values {
		b.AllowedValues = append(b.AllowedValues, values[i])
	}
	return b
}
