// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MonitoredResourceTypeGVKApplyConfiguration represents a declarative configuration of the MonitoredResourceTypeGVK type for use
// with apply.
//
// MonitoredResourceTypeGVK identifies the Kubernetes Kind this resource
// type is bound to. Version is intentionally excluded so that API
// version evolution does not require a new MonitoredResourceType.
type MonitoredResourceTypeGVKApplyConfiguration struct {
	// Group is the Kubernetes API group of the Kind (e.g.
	// "compute.miloapis.com"). Immutable.
	Group *string `json:"group,omitempty"`
	// Kind is the Kubernetes Kind (e.g. "Instance"). Immutable.
	Kind *string `json:"kind,omitempty"`
}

// MonitoredResourceTypeGVKApplyConfiguration constructs a declarative configuration of the MonitoredResourceTypeGVK type for use with
// apply.
func MonitoredResourceTypeGVK() *MonitoredResourceTypeGVKApplyConfiguration {
	return &MonitoredResourceTypeGVKApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *MonitoredResourceTypeGVKApplyConfiguration) WithGroup(value string) *MonitoredResourceTypeGVKApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MonitoredResourceTypeGVKApplyConfiguration) WithKind(value string) *MonitoredResourceTypeGVKApplyConfiguration {
	b.Kind = &value
	return b
}
