// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MonitoredResourceTypeStatusApplyConfiguration represents a declarative configuration of the MonitoredResourceTypeStatus type for use
// with apply.
//
// MonitoredResourceTypeStatus defines the observed state of a
// MonitoredResourceType.
type MonitoredResourceTypeStatusApplyConfiguration struct {
	// CatalogStatus embeds the shared catalog lifecycle fields
	// (publishedAt, conditions, observedGeneration). Phase lives on
	// spec; status mirrors it via the Published condition.
	CatalogStatusApplyConfiguration `json:",inline"`
}

// MonitoredResourceTypeStatusApplyConfiguration constructs a declarative configuration of the MonitoredResourceTypeStatus type for use with
// apply.
func MonitoredResourceTypeStatus() *MonitoredResourceTypeStatusApplyConfiguration {
	return &MonitoredResourceTypeStatusApplyConfiguration{}
}

// WithPublishedAt sets the PublishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishedAt field is set to the value of the last call.
func (b *MonitoredResourceTypeStatusApplyConfiguration) WithPublishedAt(value v1.Time) *MonitoredResourceTypeStatusApplyConfiguration {
	b.CatalogStatusApplyConfiguration.PublishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MonitoredResourceTypeStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MonitoredResourceTypeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.CatalogStatusApplyConfiguration.Conditions = append(b.CatalogStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MonitoredResourceTypeStatusApplyConfiguration) WithObservedGeneration(value int64) *MonitoredResourceTypeStatusApplyConfiguration {
	b.CatalogStatusApplyConfiguration.ObservedGeneration = &value
	return b
}
