// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// OfferStatusApplyConfiguration represents a declarative configuration of the OfferStatus type for use
// with apply.
//
// OfferStatus defines the observed state of an Offer.
type OfferStatusApplyConfiguration struct {
	// PublishedAt is the time at which the controller first observed the
	// Offer in the GA launch stage with a complete snapshot.
	PublishedAt *v1.Time `json:"publishedAt,omitempty"`
	// Conditions represent the latest available observations of the
	// Offer's state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the
	// controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// OfferStatusApplyConfiguration constructs a declarative configuration of the OfferStatus type for use with
// apply.
func OfferStatus() *OfferStatusApplyConfiguration {
	return &OfferStatusApplyConfiguration{}
}

// WithPublishedAt sets the PublishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishedAt field is set to the value of the last call.
func (b *OfferStatusApplyConfiguration) WithPublishedAt(value v1.Time) *OfferStatusApplyConfiguration {
	b.PublishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OfferStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *OfferStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *OfferStatusApplyConfiguration) WithObservedGeneration(value int64) *OfferStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
