// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OfferReferenceApplyConfiguration represents a declarative configuration of the OfferReference type for use
// with apply.
//
// OfferReference names a cluster-scoped Offer.
type OfferReferenceApplyConfiguration struct {
	// Name of the Offer.
	Name *string `json:"name,omitempty"`
}

// OfferReferenceApplyConfiguration constructs a declarative configuration of the OfferReference type for use with
// apply.
func OfferReference() *OfferReferenceApplyConfiguration {
	return &OfferReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OfferReferenceApplyConfiguration) WithName(value string) *OfferReferenceApplyConfiguration {
	b.Name = &value
	return b
}
