// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// OfferSpecApplyConfiguration represents a declarative configuration of the OfferSpec type for use
// with apply.
//
// OfferSpec defines the desired state of an Offer.
//
// An Offer bundles ServicePricings into a named, versioned tier. While
// Draft, the platform owner references ServicePricings by name via
// servicePricingRefs. On publish (launchStage=GA) the controller snapshots
// rates into servicePricings; afterward the Offer is immutable except for
// the kubernetes.io/display-name annotation.
type OfferSpecApplyConfiguration struct {
	// ChargeTypes enumerates every charge type present in the referenced
	// (or snapshotted) pricings. Required so controllers can gate on
	// charge type explicitly.
	ChargeTypes []apiv1alpha1.ChargeType `json:"chargeTypes,omitempty"`
	// LaunchStage is the Offer lifecycle stage. Draft Offers are mutable
	// and not assignable; GA Offers are published and immutable except for
	// the display-name annotation.
	LaunchStage *apiv1alpha1.OfferLaunchStage `json:"launchStage,omitempty"`
	// ServicePricingRefs names the ServicePricing resources to include.
	// Authored while Draft; retained for audit after publish. Runtime
	// rating uses servicePricings only.
	ServicePricingRefs []ServicePricingRefApplyConfiguration `json:"servicePricingRefs,omitempty"`
	// ServicePricings is an immutable snapshot of referenced
	// ServicePricing specs, written by the controller when launchStage
	// first becomes GA. Empty while Draft.
	ServicePricings []ServicePricingSnapshotApplyConfiguration `json:"servicePricings,omitempty"`
}

// OfferSpecApplyConfiguration constructs a declarative configuration of the OfferSpec type for use with
// apply.
func OfferSpec() *OfferSpecApplyConfiguration {
	return &OfferSpecApplyConfiguration{}
}

// WithChargeTypes adds the given value to the ChargeTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ChargeTypes field.
func (b *OfferSpecApplyConfiguration) WithChargeTypes(values ...apiv1alpha1.ChargeType) *OfferSpecApplyConfiguration {
	for i := range values {
		b.ChargeTypes = append(b.ChargeTypes, values[i])
	}
	return b
}

// WithLaunchStage sets the LaunchStage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LaunchStage field is set to the value of the last call.
func (b *OfferSpecApplyConfiguration) WithLaunchStage(value apiv1alpha1.OfferLaunchStage) *OfferSpecApplyConfiguration {
	b.LaunchStage = &value
	return b
}

// WithServicePricingRefs adds the given value to the ServicePricingRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServicePricingRefs field.
func (b *OfferSpecApplyConfiguration) WithServicePricingRefs(values ...*ServicePricingRefApplyConfiguration) *OfferSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServicePricingRefs")
		}
		b.ServicePricingRefs = append(b.ServicePricingRefs, *values[i])
	}
	return b
}

// WithServicePricings adds the given value to the ServicePricings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServicePricings field.
func (b *OfferSpecApplyConfiguration) WithServicePricings(values ...*ServicePricingSnapshotApplyConfiguration) *OfferSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServicePricings")
		}
		b.ServicePricings = append(b.ServicePricings, *values[i])
	}
	return b
}
