// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentTermsApplyConfiguration represents a declarative configuration of the PaymentTerms type for use
// with apply.
//
// PaymentTerms defines the payment schedule for a billing account.
type PaymentTermsApplyConfiguration struct {
	// NetDays is the number of days after invoice date that payment is due.
	NetDays *int32 `json:"netDays,omitempty"`
	// InvoiceFrequency determines how often invoices are generated.
	InvoiceFrequency *string `json:"invoiceFrequency,omitempty"`
	// InvoiceDayOfMonth is the day of the month invoices are generated.
	InvoiceDayOfMonth *int32 `json:"invoiceDayOfMonth,omitempty"`
}

// PaymentTermsApplyConfiguration constructs a declarative configuration of the PaymentTerms type for use with
// apply.
func PaymentTerms() *PaymentTermsApplyConfiguration {
	return &PaymentTermsApplyConfiguration{}
}

// WithNetDays sets the NetDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetDays field is set to the value of the last call.
func (b *PaymentTermsApplyConfiguration) WithNetDays(value int32) *PaymentTermsApplyConfiguration {
	b.NetDays = &value
	return b
}

// WithInvoiceFrequency sets the InvoiceFrequency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InvoiceFrequency field is set to the value of the last call.
func (b *PaymentTermsApplyConfiguration) WithInvoiceFrequency(value string) *PaymentTermsApplyConfiguration {
	b.InvoiceFrequency = &value
	return b
}

// WithInvoiceDayOfMonth sets the InvoiceDayOfMonth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InvoiceDayOfMonth field is set to the value of the last call.
func (b *PaymentTermsApplyConfiguration) WithInvoiceDayOfMonth(value int32) *PaymentTermsApplyConfiguration {
	b.InvoiceDayOfMonth = &value
	return b
}
