// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodClassParametersRefApplyConfiguration represents a declarative configuration of the PaymentMethodClassParametersRef type for use
// with apply.
//
// PaymentMethodClassParametersRef points at a provider-specific
// configuration resource.
type PaymentMethodClassParametersRefApplyConfiguration struct {
	// Group is the API group of the provider-specific configuration
	// resource (e.g. "stripe.billing.miloapis.com").
	Group *string `json:"group,omitempty"`
	// Kind is the Kind of the provider-specific configuration resource
	// (e.g. "StripeProviderConfig").
	Kind *string `json:"kind,omitempty"`
	// Name is the name of the provider-specific configuration resource.
	Name *string `json:"name,omitempty"`
}

// PaymentMethodClassParametersRefApplyConfiguration constructs a declarative configuration of the PaymentMethodClassParametersRef type for use with
// apply.
func PaymentMethodClassParametersRef() *PaymentMethodClassParametersRefApplyConfiguration {
	return &PaymentMethodClassParametersRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PaymentMethodClassParametersRefApplyConfiguration) WithGroup(value string) *PaymentMethodClassParametersRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PaymentMethodClassParametersRefApplyConfiguration) WithKind(value string) *PaymentMethodClassParametersRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PaymentMethodClassParametersRefApplyConfiguration) WithName(value string) *PaymentMethodClassParametersRefApplyConfiguration {
	b.Name = &value
	return b
}
