// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodUSBankAccountDetailsApplyConfiguration represents a declarative configuration of the PaymentMethodUSBankAccountDetails type for use
// with apply.
//
// PaymentMethodUSBankAccountDetails carries the public-safe metadata of a
// confirmed US bank account instrument.
type PaymentMethodUSBankAccountDetailsApplyConfiguration struct {
	// BankName is the name of the bank holding the account.
	BankName *string `json:"bankName,omitempty"`
	// Last4 is the last four digits of the account number.
	Last4 *string `json:"last4,omitempty"`
	// AccountType is the type of account (e.g. "checking", "savings").
	AccountType *string `json:"accountType,omitempty"`
}

// PaymentMethodUSBankAccountDetailsApplyConfiguration constructs a declarative configuration of the PaymentMethodUSBankAccountDetails type for use with
// apply.
func PaymentMethodUSBankAccountDetails() *PaymentMethodUSBankAccountDetailsApplyConfiguration {
	return &PaymentMethodUSBankAccountDetailsApplyConfiguration{}
}

// WithBankName sets the BankName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BankName field is set to the value of the last call.
func (b *PaymentMethodUSBankAccountDetailsApplyConfiguration) WithBankName(value string) *PaymentMethodUSBankAccountDetailsApplyConfiguration {
	b.BankName = &value
	return b
}

// WithLast4 sets the Last4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Last4 field is set to the value of the last call.
func (b *PaymentMethodUSBankAccountDetailsApplyConfiguration) WithLast4(value string) *PaymentMethodUSBankAccountDetailsApplyConfiguration {
	b.Last4 = &value
	return b
}

// WithAccountType sets the AccountType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountType field is set to the value of the last call.
func (b *PaymentMethodUSBankAccountDetailsApplyConfiguration) WithAccountType(value string) *PaymentMethodUSBankAccountDetailsApplyConfiguration {
	b.AccountType = &value
	return b
}
