// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// PaymentMethodDetailsApplyConfiguration represents a declarative configuration of the PaymentMethodDetails type for use
// with apply.
//
// PaymentMethodDetails is the normalized, provider-agnostic description
// of a confirmed payment instrument. Provider-specific identifiers are
// not exposed here — they live on the provider-owned CRD and are
// consumed only by the provider controller.
//
// PaymentMethodDetails itself is only populated once
// PaymentMethod.status.phase is Active. Within it, instrument-
// identifying fields (`card.brand`, `card.last4`, `card.expiryMonth`,
// `card.expiryYear`, `card.country`) are required because every major
// processor returns them and the portal + fraud scoring depend on
// them. Best-effort fields (BIN, AVS, CVC, billing address) remain
// optional.
type PaymentMethodDetailsApplyConfiguration struct {
	// Type identifies the instrument category.
	Type *apiv1alpha1.PaymentMethodInstrumentType `json:"type,omitempty"`
	// Card is populated when Type is `card`.
	Card *PaymentMethodCardDetailsApplyConfiguration `json:"card,omitempty"`
	// USBankAccount is populated when Type is `usBankAccount`.
	USBankAccount *PaymentMethodUSBankAccountDetailsApplyConfiguration `json:"usBankAccount,omitempty"`
}

// PaymentMethodDetailsApplyConfiguration constructs a declarative configuration of the PaymentMethodDetails type for use with
// apply.
func PaymentMethodDetails() *PaymentMethodDetailsApplyConfiguration {
	return &PaymentMethodDetailsApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PaymentMethodDetailsApplyConfiguration) WithType(value apiv1alpha1.PaymentMethodInstrumentType) *PaymentMethodDetailsApplyConfiguration {
	b.Type = &value
	return b
}

// WithCard sets the Card field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Card field is set to the value of the last call.
func (b *PaymentMethodDetailsApplyConfiguration) WithCard(value *PaymentMethodCardDetailsApplyConfiguration) *PaymentMethodDetailsApplyConfiguration {
	b.Card = value
	return b
}

// WithUSBankAccount sets the USBankAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the USBankAccount field is set to the value of the last call.
func (b *PaymentMethodDetailsApplyConfiguration) WithUSBankAccount(value *PaymentMethodUSBankAccountDetailsApplyConfiguration) *PaymentMethodDetailsApplyConfiguration {
	b.USBankAccount = value
	return b
}
