// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodClassRefApplyConfiguration represents a declarative configuration of the PaymentMethodClassRef type for use
// with apply.
//
// PaymentMethodClassRef references a cluster-scoped PaymentMethodClass.
type PaymentMethodClassRefApplyConfiguration struct {
	// Name is the name of the PaymentMethodClass.
	Name *string `json:"name,omitempty"`
}

// PaymentMethodClassRefApplyConfiguration constructs a declarative configuration of the PaymentMethodClassRef type for use with
// apply.
func PaymentMethodClassRef() *PaymentMethodClassRefApplyConfiguration {
	return &PaymentMethodClassRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PaymentMethodClassRefApplyConfiguration) WithName(value string) *PaymentMethodClassRefApplyConfiguration {
	b.Name = &value
	return b
}
