// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodClassSpecApplyConfiguration represents a declarative configuration of the PaymentMethodClassSpec type for use
// with apply.
//
// PaymentMethodClassSpec defines the desired state of a PaymentMethodClass.
type PaymentMethodClassSpecApplyConfiguration struct {
	// Provider is the name of the provider controller responsible for
	// reconciling PaymentMethods of this class. The controller watches
	// PaymentMethods whose spec.paymentMethodClassRef points at a class
	// whose spec.provider matches its own identity. Examples: "stripe",
	// "braintree".
	Provider *string `json:"provider,omitempty"`
	// ParametersRef points at a provider-owned resource carrying any
	// provider-specific SDK configuration (e.g. a Stripe publishable
	// key). PaymentMethodClass intentionally carries no provider-specific
	// fields — adding a new provider must not require a billing-service
	// schema change. This mirrors the Kubernetes Gateway API
	// `parametersRef` pattern.
	ParametersRef *PaymentMethodClassParametersRefApplyConfiguration `json:"parametersRef,omitempty"`
}

// PaymentMethodClassSpecApplyConfiguration constructs a declarative configuration of the PaymentMethodClassSpec type for use with
// apply.
func PaymentMethodClassSpec() *PaymentMethodClassSpecApplyConfiguration {
	return &PaymentMethodClassSpecApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *PaymentMethodClassSpecApplyConfiguration) WithProvider(value string) *PaymentMethodClassSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithParametersRef sets the ParametersRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParametersRef field is set to the value of the last call.
func (b *PaymentMethodClassSpecApplyConfiguration) WithParametersRef(value *PaymentMethodClassParametersRefApplyConfiguration) *PaymentMethodClassSpecApplyConfiguration {
	b.ParametersRef = value
	return b
}
