// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodCardDetailsApplyConfiguration represents a declarative configuration of the PaymentMethodCardDetails type for use
// with apply.
//
// PaymentMethodCardDetails carries the public-safe metadata of a confirmed
// card instrument. Every issuer-returned field that is meaningful across
// processors belongs here; provider-specific identifiers do not. Raw card
// data (PAN, CVC) is never persisted.
type PaymentMethodCardDetailsApplyConfiguration struct {
	// Brand is the card network (e.g. "visa", "mastercard", "amex").
	// Universally returned by every major card processor and load-
	// bearing for display + routing logic.
	Brand *string `json:"brand,omitempty"`
	// Last4 is the last four digits of the card number. Universally
	// returned and load-bearing for display, deduplication, and
	// customer support.
	Last4 *string `json:"last4,omitempty"`
	// IssuerIdentificationNumber is the BIN (first 6-8 digits) of the
	// card. Issuer-returned, not provider-specific; useful for
	// downstream fraud scoring. Optional because some providers gate
	// BIN data behind enterprise tiers.
	IssuerIdentificationNumber *string `json:"issuerIdentificationNumber,omitempty"`
	// Country is the ISO 3166-1 alpha-2 country code of the issuer.
	// Load-bearing for tax determination and one of the strongest
	// fraud signals. Returned by every major card processor we expect
	// to integrate with; a provider that cannot supply it must
	// synthesize "XX" (ISO unassigned).
	Country *string `json:"country,omitempty"`
	// ExpiryMonth is the card expiration month (1-12). Cards have
	// expiry by definition; required so we can drive "your card
	// expires soon" notifications.
	ExpiryMonth *int32 `json:"expiryMonth,omitempty"`
	// ExpiryYear is the card expiration year (four digits).
	ExpiryYear *int32 `json:"expiryYear,omitempty"`
	// AVSResult is the Address Verification System result code returned
	// by the issuer (e.g. "pass", "fail", "unchecked").
	AVSResult *string `json:"avsResult,omitempty"`
	// CVCResult is the card verification value check result returned by
	// the issuer (e.g. "pass", "fail", "unchecked").
	CVCResult *string `json:"cvcResult,omitempty"`
	// BillingAddress is the cardholder address captured by the
	// provider's collection UI at confirmation. May differ from the
	// BillingAccount's address — both signals are useful to downstream
	// consumers (the portal for display, fraud for mismatch
	// detection).
	BillingAddress *CardBillingAddressApplyConfiguration `json:"billingAddress,omitempty"`
}

// PaymentMethodCardDetailsApplyConfiguration constructs a declarative configuration of the PaymentMethodCardDetails type for use with
// apply.
func PaymentMethodCardDetails() *PaymentMethodCardDetailsApplyConfiguration {
	return &PaymentMethodCardDetailsApplyConfiguration{}
}

// WithBrand sets the Brand field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Brand field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithBrand(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.Brand = &value
	return b
}

// WithLast4 sets the Last4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Last4 field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithLast4(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.Last4 = &value
	return b
}

// WithIssuerIdentificationNumber sets the IssuerIdentificationNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerIdentificationNumber field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithIssuerIdentificationNumber(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.IssuerIdentificationNumber = &value
	return b
}

// WithCountry sets the Country field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Country field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithCountry(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.Country = &value
	return b
}

// WithExpiryMonth sets the ExpiryMonth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiryMonth field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithExpiryMonth(value int32) *PaymentMethodCardDetailsApplyConfiguration {
	b.ExpiryMonth = &value
	return b
}

// WithExpiryYear sets the ExpiryYear field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiryYear field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithExpiryYear(value int32) *PaymentMethodCardDetailsApplyConfiguration {
	b.ExpiryYear = &value
	return b
}

// WithAVSResult sets the AVSResult field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AVSResult field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithAVSResult(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.AVSResult = &value
	return b
}

// WithCVCResult sets the CVCResult field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CVCResult field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithCVCResult(value string) *PaymentMethodCardDetailsApplyConfiguration {
	b.CVCResult = &value
	return b
}

// WithBillingAddress sets the BillingAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAddress field is set to the value of the last call.
func (b *PaymentMethodCardDetailsApplyConfiguration) WithBillingAddress(value *CardBillingAddressApplyConfiguration) *PaymentMethodCardDetailsApplyConfiguration {
	b.BillingAddress = value
	return b
}
