// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PaymentMethodSpecApplyConfiguration represents a declarative configuration of the PaymentMethodSpec type for use
// with apply.
//
// PaymentMethodSpec defines the desired state of a PaymentMethod.
type PaymentMethodSpecApplyConfiguration struct {
	// BillingAccountRef references the BillingAccount this payment method
	// belongs to. The BillingAccount must reside in the same namespace.
	BillingAccountRef *BillingAccountRefApplyConfiguration `json:"billingAccountRef,omitempty"`
	// DisplayName is a human-readable label shown in the portal and on
	// invoices (e.g. "Corporate Visa").
	DisplayName *string `json:"displayName,omitempty"`
	// PaymentMethodClassRef selects the PaymentMethodClass — and through
	// it the provider controller — that owns the setup flow for this
	// payment method. Left unset by consumers and injected by the
	// defaulting webhook from the cluster default class. Immutable once
	// set; changing it would orphan provider-side state.
	PaymentMethodClassRef *PaymentMethodClassRefApplyConfiguration `json:"paymentMethodClassRef,omitempty"`
}

// PaymentMethodSpecApplyConfiguration constructs a declarative configuration of the PaymentMethodSpec type for use with
// apply.
func PaymentMethodSpec() *PaymentMethodSpecApplyConfiguration {
	return &PaymentMethodSpecApplyConfiguration{}
}

// WithBillingAccountRef sets the BillingAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BillingAccountRef field is set to the value of the last call.
func (b *PaymentMethodSpecApplyConfiguration) WithBillingAccountRef(value *BillingAccountRefApplyConfiguration) *PaymentMethodSpecApplyConfiguration {
	b.BillingAccountRef = value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *PaymentMethodSpecApplyConfiguration) WithDisplayName(value string) *PaymentMethodSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithPaymentMethodClassRef sets the PaymentMethodClassRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PaymentMethodClassRef field is set to the value of the last call.
func (b *PaymentMethodSpecApplyConfiguration) WithPaymentMethodClassRef(value *PaymentMethodClassRefApplyConfiguration) *PaymentMethodSpecApplyConfiguration {
	b.PaymentMethodClassRef = value
	return b
}
