// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PaymentMethodStatusApplyConfiguration represents a declarative configuration of the PaymentMethodStatus type for use
// with apply.
//
// PaymentMethodStatus defines the observed state of a PaymentMethod.
type PaymentMethodStatusApplyConfiguration struct {
	// Phase represents the current lifecycle phase.
	Phase *apiv1alpha1.PaymentMethodPhase `json:"phase,omitempty"`
	// Details is the normalized, provider-agnostic description of the
	// confirmed instrument. Populated by the owning provider controller
	// once the phase reaches Active.
	Details *PaymentMethodDetailsApplyConfiguration `json:"details,omitempty"`
	// FailureReason is a short, machine-parseable code for the failure
	// (e.g. "card_declined", "setup_intent_expired"). Set when phase is
	// Failed.
	FailureReason *string `json:"failureReason,omitempty"`
	// FailureMessage is a human-readable description of the failure.
	FailureMessage *string `json:"failureMessage,omitempty"`
	// Conditions represent the latest available observations of the
	// payment method's state. See PaymentMethodConditionInstrumentReady.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the
	// reconciling controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// PaymentMethodStatusApplyConfiguration constructs a declarative configuration of the PaymentMethodStatus type for use with
// apply.
func PaymentMethodStatus() *PaymentMethodStatusApplyConfiguration {
	return &PaymentMethodStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PaymentMethodStatusApplyConfiguration) WithPhase(value apiv1alpha1.PaymentMethodPhase) *PaymentMethodStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDetails sets the Details field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Details field is set to the value of the last call.
func (b *PaymentMethodStatusApplyConfiguration) WithDetails(value *PaymentMethodDetailsApplyConfiguration) *PaymentMethodStatusApplyConfiguration {
	b.Details = value
	return b
}

// WithFailureReason sets the FailureReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureReason field is set to the value of the last call.
func (b *PaymentMethodStatusApplyConfiguration) WithFailureReason(value string) *PaymentMethodStatusApplyConfiguration {
	b.FailureReason = &value
	return b
}

// WithFailureMessage sets the FailureMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureMessage field is set to the value of the last call.
func (b *PaymentMethodStatusApplyConfiguration) WithFailureMessage(value string) *PaymentMethodStatusApplyConfiguration {
	b.FailureMessage = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PaymentMethodStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PaymentMethodStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PaymentMethodStatusApplyConfiguration) WithObservedGeneration(value int64) *PaymentMethodStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
