// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PaymentMethodClassStatusApplyConfiguration represents a declarative configuration of the PaymentMethodClassStatus type for use
// with apply.
//
// PaymentMethodClassStatus defines the observed state of a PaymentMethodClass.
type PaymentMethodClassStatusApplyConfiguration struct {
	// Conditions represent the latest available observations of the
	// class's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the most recent generation observed by the
	// controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// PaymentMethodClassStatusApplyConfiguration constructs a declarative configuration of the PaymentMethodClassStatus type for use with
// apply.
func PaymentMethodClassStatus() *PaymentMethodClassStatusApplyConfiguration {
	return &PaymentMethodClassStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PaymentMethodClassStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PaymentMethodClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PaymentMethodClassStatusApplyConfiguration) WithObservedGeneration(value int64) *PaymentMethodClassStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
