// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PricingRateApplyConfiguration represents a declarative configuration of the PricingRate type for use
// with apply.
//
// PricingRate is a single rate entry. Exactly one of Flat or Tiered must
// be set. An optional Match filters the rate by dimension value; the last
// unmatched entry is the default catch-all in Milo.
//
// Note: the Amberflo provider cannot materialize mixed match + unmatched
// catch-all rates today (DimensionMatrixNode has no default bucket). When
// targeting that backend, price every dimension value explicitly — use a
// sentinel match value the meter emits (e.g. "other") for fallbacks.
type PricingRateApplyConfiguration struct {
	// Match optionally restricts this rate to a single dimension value.
	Match *DimensionMatchApplyConfiguration `json:"match,omitempty"`
	// Flat is a single decimal USD string multiplied by metered usage.
	// Mutually exclusive with Tiered.
	Flat *string `json:"flat,omitempty"`
	// Tiered is an ordered list of graduated volume bands.
	// Mutually exclusive with Flat.
	Tiered []PricingTierBandApplyConfiguration `json:"tiered,omitempty"`
}

// PricingRateApplyConfiguration constructs a declarative configuration of the PricingRate type for use with
// apply.
func PricingRate() *PricingRateApplyConfiguration {
	return &PricingRateApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *PricingRateApplyConfiguration) WithMatch(value *DimensionMatchApplyConfiguration) *PricingRateApplyConfiguration {
	b.Match = value
	return b
}

// WithFlat sets the Flat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Flat field is set to the value of the last call.
func (b *PricingRateApplyConfiguration) WithFlat(value string) *PricingRateApplyConfiguration {
	b.Flat = &value
	return b
}

// WithTiered adds the given value to the Tiered field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tiered field.
func (b *PricingRateApplyConfiguration) WithTiered(values ...*PricingTierBandApplyConfiguration) *PricingRateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTiered")
		}
		b.Tiered = append(b.Tiered, *values[i])
	}
	return b
}
