// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PricingTierBandApplyConfiguration represents a declarative configuration of the PricingTierBand type for use
// with apply.
//
// PricingTierBand is a single graduated volume band. Aggregation for
// tier breaks is monthly at billing-account scope. Each band has a rate
// and an exclusive upper bound upTo in pricingUnit units. The last band
// omits upTo (open-ended).
type PricingTierBandApplyConfiguration struct {
	// UpTo is the exclusive upper bound of this band in pricingUnit units.
	// Omit on the last band for an open-ended range.
	UpTo *string `json:"upTo,omitempty"`
	// Rate is the USD decimal string applied to usage within this band.
	// Zero ("0") is valid for free allowances.
	Rate *string `json:"rate,omitempty"`
}

// PricingTierBandApplyConfiguration constructs a declarative configuration of the PricingTierBand type for use with
// apply.
func PricingTierBand() *PricingTierBandApplyConfiguration {
	return &PricingTierBandApplyConfiguration{}
}

// WithUpTo sets the UpTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpTo field is set to the value of the last call.
func (b *PricingTierBandApplyConfiguration) WithUpTo(value string) *PricingTierBandApplyConfiguration {
	b.UpTo = &value
	return b
}

// WithRate sets the Rate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rate field is set to the value of the last call.
func (b *PricingTierBandApplyConfiguration) WithRate(value string) *PricingTierBandApplyConfiguration {
	b.Rate = &value
	return b
}
