// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProjectRefApplyConfiguration represents a declarative configuration of the ProjectRef type for use
// with apply.
//
// ProjectRef is a reference to a project by name.
type ProjectRefApplyConfiguration struct {
	// Name is the name of the project.
	Name *string `json:"name,omitempty"`
}

// ProjectRefApplyConfiguration constructs a declarative configuration of the ProjectRef type for use with
// apply.
func ProjectRef() *ProjectRefApplyConfiguration {
	return &ProjectRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ProjectRefApplyConfiguration) WithName(value string) *ProjectRefApplyConfiguration {
	b.Name = &value
	return b
}
