// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.miloapis.com/billing/api/v1alpha1"
)

// ServicePricingSpecApplyConfiguration represents a declarative configuration of the ServicePricingSpec type for use
// with apply.
//
// ServicePricingSpec defines the desired state of a ServicePricing.
//
// ServicePricing resources are emitted by service-catalog fan-out
// controllers (PricingFanOut / ChargeFanOut) and must not be authored by
// hand. Providers watch this single shape — distinguished by chargeType —
// rather than parsing ServiceConfiguration.
type ServicePricingSpecApplyConfiguration struct {
	// ChargeType distinguishes Usage, OneTime, and Recurring pricing.
	ChargeType *apiv1alpha1.ChargeType `json:"chargeType,omitempty"`
	// ServiceRef is the canonical service identifier (e.g.
	// "compute.datumapis.com").
	ServiceRef *string `json:"serviceRef,omitempty"`
	// Currency is the ISO 4217 currency code. USD only in v1.
	Currency *string `json:"currency,omitempty"`
	// DisplayName is a human-readable label for invoices and portals.
	DisplayName *string `json:"displayName,omitempty"`
	// Metric is the full metric name for Usage charges (e.g.
	// "compute.datumapis.com/instance/cpu-allocated"). Required when
	// chargeType is Usage.
	Metric *string `json:"metric,omitempty"`
	// PricingUnit is a human-readable billing unit label (e.g. "vcpu",
	// "gib"). Required when chargeType is Usage. Does not need to be the
	// literal UCUM unit string of the meter.
	PricingUnit *string `json:"pricingUnit,omitempty"`
	// Rates is the ordered list of rate entries for Usage charges.
	// Required when chargeType is Usage.
	Rates []PricingRateApplyConfiguration `json:"rates,omitempty"`
	// Amount is the fixed USD decimal string for OneTime and Recurring
	// charges.
	Amount *string `json:"amount,omitempty"`
	// Trigger identifies when a OneTime charge fires.
	Trigger *apiv1alpha1.ChargeTrigger `json:"trigger,omitempty"`
	// Interval is the cadence for a Recurring charge.
	Interval *apiv1alpha1.ChargeInterval `json:"interval,omitempty"`
}

// ServicePricingSpecApplyConfiguration constructs a declarative configuration of the ServicePricingSpec type for use with
// apply.
func ServicePricingSpec() *ServicePricingSpecApplyConfiguration {
	return &ServicePricingSpecApplyConfiguration{}
}

// WithChargeType sets the ChargeType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChargeType field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithChargeType(value apiv1alpha1.ChargeType) *ServicePricingSpecApplyConfiguration {
	b.ChargeType = &value
	return b
}

// WithServiceRef sets the ServiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceRef field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithServiceRef(value string) *ServicePricingSpecApplyConfiguration {
	b.ServiceRef = &value
	return b
}

// WithCurrency sets the Currency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Currency field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithCurrency(value string) *ServicePricingSpecApplyConfiguration {
	b.Currency = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithDisplayName(value string) *ServicePricingSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithMetric sets the Metric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metric field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithMetric(value string) *ServicePricingSpecApplyConfiguration {
	b.Metric = &value
	return b
}

// WithPricingUnit sets the PricingUnit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PricingUnit field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithPricingUnit(value string) *ServicePricingSpecApplyConfiguration {
	b.PricingUnit = &value
	return b
}

// WithRates adds the given value to the Rates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rates field.
func (b *ServicePricingSpecApplyConfiguration) WithRates(values ...*PricingRateApplyConfiguration) *ServicePricingSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRates")
		}
		b.Rates = append(b.Rates, *values[i])
	}
	return b
}

// WithAmount sets the Amount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Amount field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithAmount(value string) *ServicePricingSpecApplyConfiguration {
	b.Amount = &value
	return b
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithTrigger(value apiv1alpha1.ChargeTrigger) *ServicePricingSpecApplyConfiguration {
	b.Trigger = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *ServicePricingSpecApplyConfiguration) WithInterval(value apiv1alpha1.ChargeInterval) *ServicePricingSpecApplyConfiguration {
	b.Interval = &value
	return b
}
