// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServicePricingSnapshotApplyConfiguration represents a declarative configuration of the ServicePricingSnapshot type for use
// with apply.
//
// ServicePricingSnapshot is an immutable copy of a ServicePricingSpec taken
// at Offer publish time, plus the source ServicePricing name.
type ServicePricingSnapshotApplyConfiguration struct {
	// Name is the metadata.name of the source ServicePricing.
	Name *string `json:"name,omitempty"`
	// Spec is a deep copy of the source ServicePricingSpec at publish time.
	Spec *ServicePricingSpecApplyConfiguration `json:"spec,omitempty"`
}

// ServicePricingSnapshotApplyConfiguration constructs a declarative configuration of the ServicePricingSnapshot type for use with
// apply.
func ServicePricingSnapshot() *ServicePricingSnapshotApplyConfiguration {
	return &ServicePricingSnapshotApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServicePricingSnapshotApplyConfiguration) WithName(value string) *ServicePricingSnapshotApplyConfiguration {
	b.Name = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ServicePricingSnapshotApplyConfiguration) WithSpec(value *ServicePricingSpecApplyConfiguration) *ServicePricingSnapshotApplyConfiguration {
	b.Spec = value
	return b
}
