// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServicePricingRefApplyConfiguration represents a declarative configuration of the ServicePricingRef type for use
// with apply.
//
// ServicePricingRef names a ServicePricing resource referenced by an Offer
// while in Draft. Namespace defaults to milo-system when omitted.
type ServicePricingRefApplyConfiguration struct {
	// Name is the metadata.name of the ServicePricing.
	Name *string `json:"name,omitempty"`
	// Namespace is the namespace of the ServicePricing. Defaults to
	// milo-system when empty.
	Namespace *string `json:"namespace,omitempty"`
}

// ServicePricingRefApplyConfiguration constructs a declarative configuration of the ServicePricingRef type for use with
// apply.
func ServicePricingRef() *ServicePricingRefApplyConfiguration {
	return &ServicePricingRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServicePricingRefApplyConfiguration) WithName(value string) *ServicePricingRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ServicePricingRefApplyConfiguration) WithNamespace(value string) *ServicePricingRefApplyConfiguration {
	b.Namespace = &value
	return b
}
