// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TaxIDApplyConfiguration represents a declarative configuration of the TaxID type for use
// with apply.
//
// TaxID is a single tax registration.
//
// Type values follow a vendor-neutral snake-case
// `<jurisdiction>_<scheme>` convention — e.g. "gb_vat", "eu_vat",
// "us_ein", "au_abn", "ca_gst_hst", "ch_vat", "in_gst", "sg_gst".
// The pattern check enforces the shape rather than the exact set of
// values, so new schemes can be added without API changes.
// Translation to any provider-specific identifier (if needed) is the
// responsibility of the provider controller, not this schema.
type TaxIDApplyConfiguration struct {
	// Type identifies the tax registration scheme (e.g. "gb_vat").
	Type *string `json:"type,omitempty"`
	// Value is the registration number / identifier
	// (e.g. "GB123456789").
	Value *string `json:"value,omitempty"`
}

// TaxIDApplyConfiguration constructs a declarative configuration of the TaxID type for use with
// apply.
func TaxID() *TaxIDApplyConfiguration {
	return &TaxIDApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *TaxIDApplyConfiguration) WithType(value string) *TaxIDApplyConfiguration {
	b.Type = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *TaxIDApplyConfiguration) WithValue(value string) *TaxIDApplyConfiguration {
	b.Value = &value
	return b
}
