---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: billing-controller-manager
rules:
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings
  - billingaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/finalizers
  - billingaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/status
  - billingaccounts/status
  verbs:
  - get
  - patch
  - update
