---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: billing-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings
  - billingaccounts
  - meterdefinitions
  - monitoredresourcetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/finalizers
  - billingaccounts/finalizers
  - meterdefinitions/finalizers
  - monitoredresourcetypes/finalizers
  verbs:
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/status
  - billingaccounts/status
  - meterdefinitions/status
  - monitoredresourcetypes/status
  - paymentmethodsetups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - paymentmethodsetups
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - paymentproviders
  verbs:
  - get
  - list
  - watch
