---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: billing-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings
  - billingaccounts
  - billingentitlements
  - meterdefinitions
  - monitoredresourcetypes
  - offers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/finalizers
  - billingaccounts/finalizers
  - billingentitlements/finalizers
  - meterdefinitions/finalizers
  - monitoredresourcetypes/finalizers
  - offers/finalizers
  verbs:
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings/status
  - billingaccounts/status
  - billingentitlements/status
  - meterdefinitions/status
  - monitoredresourcetypes/status
  - offers/status
  - paymentmethods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - invoices
  - paymentmethodclasses
  - paymentmethods
  - servicepricings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
