apiVersion: billing.miloapis.com/v1alpha1
kind: BillingAccount
metadata:
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/managed-by: kustomize
  name: billingaccount-sample
spec:
  currencyCode: USD
  paymentTerms:
    netDays: 30
    invoiceFrequency: Monthly
    invoiceDayOfMonth: 1
  contactInfo:
    email: billing@example.com
    name: Billing Department
