//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccount) DeepCopyInto(out *BillingAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccount.
func (in *BillingAccount) DeepCopy() *BillingAccount {
	if in == nil {
		return nil
	}
	out := new(BillingAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountBinding) DeepCopyInto(out *BillingAccountBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountBinding.
func (in *BillingAccountBinding) DeepCopy() *BillingAccountBinding {
	if in == nil {
		return nil
	}
	out := new(BillingAccountBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingAccountBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountBindingList) DeepCopyInto(out *BillingAccountBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BillingAccountBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountBindingList.
func (in *BillingAccountBindingList) DeepCopy() *BillingAccountBindingList {
	if in == nil {
		return nil
	}
	out := new(BillingAccountBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingAccountBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountBindingSpec) DeepCopyInto(out *BillingAccountBindingSpec) {
	*out = *in
	out.BillingAccountRef = in.BillingAccountRef
	out.ProjectRef = in.ProjectRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountBindingSpec.
func (in *BillingAccountBindingSpec) DeepCopy() *BillingAccountBindingSpec {
	if in == nil {
		return nil
	}
	out := new(BillingAccountBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountBindingStatus) DeepCopyInto(out *BillingAccountBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BillingResponsibility != nil {
		in, out := &in.BillingResponsibility, &out.BillingResponsibility
		*out = new(BillingResponsibility)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountBindingStatus.
func (in *BillingAccountBindingStatus) DeepCopy() *BillingAccountBindingStatus {
	if in == nil {
		return nil
	}
	out := new(BillingAccountBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountList) DeepCopyInto(out *BillingAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BillingAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountList.
func (in *BillingAccountList) DeepCopy() *BillingAccountList {
	if in == nil {
		return nil
	}
	out := new(BillingAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountRef) DeepCopyInto(out *BillingAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountRef.
func (in *BillingAccountRef) DeepCopy() *BillingAccountRef {
	if in == nil {
		return nil
	}
	out := new(BillingAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountSpec) DeepCopyInto(out *BillingAccountSpec) {
	*out = *in
	if in.PaymentTerms != nil {
		in, out := &in.PaymentTerms, &out.PaymentTerms
		*out = new(PaymentTerms)
		**out = **in
	}
	if in.ContactInfo != nil {
		in, out := &in.ContactInfo, &out.ContactInfo
		*out = new(BillingContactInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TaxIDs != nil {
		in, out := &in.TaxIDs, &out.TaxIDs
		*out = make([]TaxID, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPaymentMethodRef != nil {
		in, out := &in.DefaultPaymentMethodRef, &out.DefaultPaymentMethodRef
		*out = new(DefaultPaymentMethodRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountSpec.
func (in *BillingAccountSpec) DeepCopy() *BillingAccountSpec {
	if in == nil {
		return nil
	}
	out := new(BillingAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAccountStatus) DeepCopyInto(out *BillingAccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAccountStatus.
func (in *BillingAccountStatus) DeepCopy() *BillingAccountStatus {
	if in == nil {
		return nil
	}
	out := new(BillingAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingAddress) DeepCopyInto(out *BillingAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingAddress.
func (in *BillingAddress) DeepCopy() *BillingAddress {
	if in == nil {
		return nil
	}
	out := new(BillingAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingContactInfo) DeepCopyInto(out *BillingContactInfo) {
	*out = *in
	if in.InvoiceEmails != nil {
		in, out := &in.InvoiceEmails, &out.InvoiceEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(BillingAddress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingContactInfo.
func (in *BillingContactInfo) DeepCopy() *BillingContactInfo {
	if in == nil {
		return nil
	}
	out := new(BillingContactInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingResponsibility) DeepCopyInto(out *BillingResponsibility) {
	*out = *in
	if in.EstablishedAt != nil {
		in, out := &in.EstablishedAt, &out.EstablishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingResponsibility.
func (in *BillingResponsibility) DeepCopy() *BillingResponsibility {
	if in == nil {
		return nil
	}
	out := new(BillingResponsibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardBillingAddress) DeepCopyInto(out *CardBillingAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardBillingAddress.
func (in *CardBillingAddress) DeepCopy() *CardBillingAddress {
	if in == nil {
		return nil
	}
	out := new(CardBillingAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogStatus) DeepCopyInto(out *CatalogStatus) {
	*out = *in
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogStatus.
func (in *CatalogStatus) DeepCopy() *CatalogStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPaymentMethodRef) DeepCopyInto(out *DefaultPaymentMethodRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPaymentMethodRef.
func (in *DefaultPaymentMethodRef) DeepCopy() *DefaultPaymentMethodRef {
	if in == nil {
		return nil
	}
	out := new(DefaultPaymentMethodRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterBilling) DeepCopyInto(out *MeterBilling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterBilling.
func (in *MeterBilling) DeepCopy() *MeterBilling {
	if in == nil {
		return nil
	}
	out := new(MeterBilling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterDefinition) DeepCopyInto(out *MeterDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterDefinition.
func (in *MeterDefinition) DeepCopy() *MeterDefinition {
	if in == nil {
		return nil
	}
	out := new(MeterDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeterDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterDefinitionList) DeepCopyInto(out *MeterDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeterDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterDefinitionList.
func (in *MeterDefinitionList) DeepCopy() *MeterDefinitionList {
	if in == nil {
		return nil
	}
	out := new(MeterDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeterDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterDefinitionSpec) DeepCopyInto(out *MeterDefinitionSpec) {
	*out = *in
	in.Measurement.DeepCopyInto(&out.Measurement)
	out.Billing = in.Billing
	if in.MonitoredResourceTypes != nil {
		in, out := &in.MonitoredResourceTypes, &out.MonitoredResourceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterDefinitionSpec.
func (in *MeterDefinitionSpec) DeepCopy() *MeterDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(MeterDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterDefinitionStatus) DeepCopyInto(out *MeterDefinitionStatus) {
	*out = *in
	in.CatalogStatus.DeepCopyInto(&out.CatalogStatus)
	if in.SystemDimensions != nil {
		in, out := &in.SystemDimensions, &out.SystemDimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterDefinitionStatus.
func (in *MeterDefinitionStatus) DeepCopy() *MeterDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(MeterDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterMeasurement) DeepCopyInto(out *MeterMeasurement) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterMeasurement.
func (in *MeterMeasurement) DeepCopy() *MeterMeasurement {
	if in == nil {
		return nil
	}
	out := new(MeterMeasurement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceLabel) DeepCopyInto(out *MonitoredResourceLabel) {
	*out = *in
	if in.AllowedValues != nil {
		in, out := &in.AllowedValues, &out.AllowedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceLabel.
func (in *MonitoredResourceLabel) DeepCopy() *MonitoredResourceLabel {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceType) DeepCopyInto(out *MonitoredResourceType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceType.
func (in *MonitoredResourceType) DeepCopy() *MonitoredResourceType {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoredResourceType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceTypeGVK) DeepCopyInto(out *MonitoredResourceTypeGVK) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceTypeGVK.
func (in *MonitoredResourceTypeGVK) DeepCopy() *MonitoredResourceTypeGVK {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceTypeGVK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceTypeList) DeepCopyInto(out *MonitoredResourceTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoredResourceType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceTypeList.
func (in *MonitoredResourceTypeList) DeepCopy() *MonitoredResourceTypeList {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoredResourceTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceTypeSpec) DeepCopyInto(out *MonitoredResourceTypeSpec) {
	*out = *in
	out.GVK = in.GVK
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]MonitoredResourceLabel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceTypeSpec.
func (in *MonitoredResourceTypeSpec) DeepCopy() *MonitoredResourceTypeSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoredResourceTypeStatus) DeepCopyInto(out *MonitoredResourceTypeStatus) {
	*out = *in
	in.CatalogStatus.DeepCopyInto(&out.CatalogStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoredResourceTypeStatus.
func (in *MonitoredResourceTypeStatus) DeepCopy() *MonitoredResourceTypeStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoredResourceTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethod) DeepCopyInto(out *PaymentMethod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethod.
func (in *PaymentMethod) DeepCopy() *PaymentMethod {
	if in == nil {
		return nil
	}
	out := new(PaymentMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodCardDetails) DeepCopyInto(out *PaymentMethodCardDetails) {
	*out = *in
	if in.BillingAddress != nil {
		in, out := &in.BillingAddress, &out.BillingAddress
		*out = new(CardBillingAddress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodCardDetails.
func (in *PaymentMethodCardDetails) DeepCopy() *PaymentMethodCardDetails {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodCardDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClass) DeepCopyInto(out *PaymentMethodClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClass.
func (in *PaymentMethodClass) DeepCopy() *PaymentMethodClass {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethodClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClassList) DeepCopyInto(out *PaymentMethodClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PaymentMethodClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClassList.
func (in *PaymentMethodClassList) DeepCopy() *PaymentMethodClassList {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethodClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClassParametersRef) DeepCopyInto(out *PaymentMethodClassParametersRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClassParametersRef.
func (in *PaymentMethodClassParametersRef) DeepCopy() *PaymentMethodClassParametersRef {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClassParametersRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClassRef) DeepCopyInto(out *PaymentMethodClassRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClassRef.
func (in *PaymentMethodClassRef) DeepCopy() *PaymentMethodClassRef {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClassRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClassSpec) DeepCopyInto(out *PaymentMethodClassSpec) {
	*out = *in
	out.ParametersRef = in.ParametersRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClassSpec.
func (in *PaymentMethodClassSpec) DeepCopy() *PaymentMethodClassSpec {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodClassStatus) DeepCopyInto(out *PaymentMethodClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodClassStatus.
func (in *PaymentMethodClassStatus) DeepCopy() *PaymentMethodClassStatus {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodDetails) DeepCopyInto(out *PaymentMethodDetails) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = new(PaymentMethodCardDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.USBankAccount != nil {
		in, out := &in.USBankAccount, &out.USBankAccount
		*out = new(PaymentMethodUSBankAccountDetails)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodDetails.
func (in *PaymentMethodDetails) DeepCopy() *PaymentMethodDetails {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodList) DeepCopyInto(out *PaymentMethodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PaymentMethod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodList.
func (in *PaymentMethodList) DeepCopy() *PaymentMethodList {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodSpec) DeepCopyInto(out *PaymentMethodSpec) {
	*out = *in
	out.BillingAccountRef = in.BillingAccountRef
	if in.PaymentMethodClassRef != nil {
		in, out := &in.PaymentMethodClassRef, &out.PaymentMethodClassRef
		*out = new(PaymentMethodClassRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodSpec.
func (in *PaymentMethodSpec) DeepCopy() *PaymentMethodSpec {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodStatus) DeepCopyInto(out *PaymentMethodStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(PaymentMethodDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodStatus.
func (in *PaymentMethodStatus) DeepCopy() *PaymentMethodStatus {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodUSBankAccountDetails) DeepCopyInto(out *PaymentMethodUSBankAccountDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodUSBankAccountDetails.
func (in *PaymentMethodUSBankAccountDetails) DeepCopy() *PaymentMethodUSBankAccountDetails {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodUSBankAccountDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentTerms) DeepCopyInto(out *PaymentTerms) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentTerms.
func (in *PaymentTerms) DeepCopy() *PaymentTerms {
	if in == nil {
		return nil
	}
	out := new(PaymentTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRef) DeepCopyInto(out *ProjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRef.
func (in *ProjectRef) DeepCopy() *ProjectRef {
	if in == nil {
		return nil
	}
	out := new(ProjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaxID) DeepCopyInto(out *TaxID) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaxID.
func (in *TaxID) DeepCopy() *TaxID {
	if in == nil {
		return nil
	}
	out := new(TaxID)
	in.DeepCopyInto(out)
	return out
}
