namespace: billing-system

images:
  - name: ghcr.io/milo-os/billing
    newTag: dev

resources:
  - ../../base/crd
  - ../../base/manager
  - ../../base/certmanager
  - ../../gateway

components:
  - ../../components/namespace
  - ../../base/webhook
  - ../../components/controller_rbac

patches:
  - path: manager_pull_policy_patch.yaml
  - target:
      kind: Certificate
      name: billing-serving-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - billing-webhook.billing-system.svc
          - billing-webhook.billing-system.svc.cluster.local
  - target:
      kind: Deployment
      name: billing-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: billing-gateway
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1

replacements:
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: billing-serving-cert
      fieldPath: .metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
          create: true
      - select:
          kind: MutatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
          create: true
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: billing-serving-cert
      fieldPath: .metadata.name
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
          create: true
      - select:
          kind: MutatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
          create: true
