apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: billing
    app.kubernetes.io/name: billing
    app.kubernetes.io/managed-by: kustomize
  name: billing-controller-manager-metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: billing
    app.kubernetes.io/name: billing
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kustomize
  name: billing-gateway-metrics
spec:
  ports:
  - name: http-metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app.kubernetes.io/name: billing
    app.kubernetes.io/component: gateway
