apiVersion: v1
kind: Service
metadata:
  name: vector-agent
  namespace: vector-agent
  labels:
    app.kubernetes.io/name: vector-agent
spec:
  # Using internalTrafficPolicy: Local ensures that pods talk to the agent on their node.
  # This avoids cross-node traffic and reduces latency for high-throughput usage events.
  internalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: vector-agent
  ports:
    - name: cloudevents
      port: 9880
      targetPort: cloudevents
      protocol: TCP
