apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configurations:
  - kustomizeconfig.yaml

resources:
  - authenticated-user-meter-definition-read.yaml
  - authenticated-user-payment-method-class-read.yaml
  - staff-billing-viewer-billingaccount.yaml
  - staff-billing-viewer-billingaccountbinding.yaml
  - staff-billing-viewer-organization.yaml
  - staff-billing-viewer-paymentmethod.yaml
